In [1]:
from pathlib import Path
import pandas as pd

# ==============================
# PaddyVision-AI - Dataset Paths
# ==============================

PROJECT_ROOT = Path(r"C:\Users\adnan\PaddyVision-AI")
RAW_DIR = PROJECT_ROOT / "data" / "raw"

WEEDY_DIR = RAW_DIR / "weedy-rice"
UAV_DIR = RAW_DIR / "rice-uav"
ICAR_DIR = RAW_DIR / "icar-rice"
HISTORICAL_DIR = RAW_DIR / "historical-rice"

print("Project root :", PROJECT_ROOT)
print("Raw data     :", RAW_DIR)

print("\nDatasets:")
for name, path in {
    "Weedy Rice": WEEDY_DIR,
    "Rice UAV": UAV_DIR,
    "ICAR Rice": ICAR_DIR,
    "Historical Rice": HISTORICAL_DIR
}.items():
    print(f"{name:20} -> {'FOUND' if path.exists() else 'NOT FOUND'}")

Project root : C:\Users\adnan\PaddyVision-AI
Raw data     : C:\Users\adnan\PaddyVision-AI\data\raw

Datasets:
Weedy Rice           -> FOUND
Rice UAV             -> FOUND
ICAR Rice            -> FOUND
Historical Rice      -> FOUND

In [2]:
# ==================================
# Inspect first-level dataset files
# ==================================

def inspect_folder(folder_path):
    print(f"\n{'=' * 60}")
    print(f"DATASET: {folder_path.name}")
    print(f"{'=' * 60}")

    if not folder_path.exists():
        print("Folder not found!")
        return

    items = list(folder_path.iterdir())

    folders = [item for item in items if item.is_dir()]
    files = [item for item in items if item.is_file()]

    print(f"Folders : {len(folders)}")
    print(f"Files   : {len(files)}")

    if folders:
        print("\nFolders:")
        for folder in sorted(folders):
            print(f"  📁 {folder.name}")

    if files:
        print("\nFiles:")
        for file in sorted(files):
            size_kb = file.stat().st_size / 1024
            print(f"  📄 {file.name}  ({size_kb:.2f} KB)")


inspect_folder(WEEDY_DIR)
inspect_folder(UAV_DIR)
inspect_folder(ICAR_DIR)
inspect_folder(HISTORICAL_DIR)

============================================================
DATASET: weedy-rice
============================================================
Folders : 5
Files   : 4

Folders:
  📁 Masks
  📁 Metadata
  📁 Multispectral
  📁 Overlay
  📁 RGB

Files:
  📄 readme.md  (5.52 KB)
  📄 test_list.txt  (11.85 KB)
  📄 train_list.txt  (35.07 KB)
  📄 val_list.txt  (11.85 KB)

============================================================
DATASET: rice-uav
============================================================
Folders : 1
Files   : 3

Folders:
  📁 riceUAS

Files:
  📄 README.md  (3.03 KB)
  📄 RREC_DAILY_2021.xlsx  (84.77 KB)
  📄 RREC_DAILY_2022.xlsx  (85.12 KB)

============================================================
DATASET: icar-rice
============================================================
Folders : 0
Files   : 1

Files:
  📄 Rice_Data_2026-09-27.csv  (1.07 KB)

============================================================
DATASET: historical-rice
============================================================
Folders : 2
Files   : 0

Folders:
  📁 Central_India_Region
  📁 Gangetic_Plain_Region

In [3]:
# ============================
# File extension distribution
# ============================

def get_file_extensions(folder_path):
    extensions = {}

    for file in folder_path.rglob("*"):
        if file.is_file():
            ext = file.suffix.lower() or "[no extension]"
            extensions[ext] = extensions.get(ext, 0) + 1

    return extensions


for name, folder in {
    "Weedy Rice": WEEDY_DIR,
    "Rice UAV": UAV_DIR,
    "ICAR Rice": ICAR_DIR,
    "Historical Rice": HISTORICAL_DIR
}.items():

    print(f"\n{name}")
    print("-" * 40)

    extensions = get_file_extensions(folder)

    for ext, count in sorted(extensions.items()):
        print(f"{ext:15} : {count}")

Weedy Rice
----------------------------------------
.csv            : 2
.jpg            : 1468
.md             : 1
.png            : 734
.tif            : 2936
.txt            : 4

Rice UAV
----------------------------------------
.csv            : 4
.ds_store       : 2
.md             : 1
.ovr            : 49752
.tfw            : 49752
.tiff           : 49752
.txt            : 4
.xlsx           : 2
.xml            : 99504
[no extension]  : 5037

ICAR Rice
----------------------------------------
.csv            : 1

Historical Rice
----------------------------------------
.xlsx           : 93

In [4]:
# ==========================================
# Inspect tabular datasets
# ==========================================

print("ICAR RICE FILES")
print("-" * 50)

icar_files = list(ICAR_DIR.glob("*.csv"))

for file in icar_files:
    print("\nFile:", file.name)

    df = pd.read_csv(file)

    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())

    print("\nFirst 5 rows:")
    display(df.head())

    print("\nMissing values:")
    print(df.isnull().sum())

ICAR RICE FILES
--------------------------------------------------

File: Rice_Data_2026-09-27.csv
Shape: (28, 1)

Columns:
['<!-- FILE: config.php -->']

First 5 rows:

                                     <!-- FILE: config.php -->
Year Area (Ha)   Production (Tonnes)             Yield (Kg/ha)
2023 47828289.10 137824576.00                          2882.00
2022 47831997.65 135755160.30                          2838.00
2021 46278675.43 129471418.20                          2798.00
2020 45768687.00 124368315.90                          2717.00

Missing values:
<!-- FILE: config.php -->    0
dtype: int64

In [5]:
# ==========================================
# Clean and inspect ICAR Rice dataset
# ==========================================

icar_file = next(ICAR_DIR.glob("*.csv"))

df_icar = pd.read_csv(
    icar_file,
    skiprows=1
)

# Set correct column names
df_icar.columns = [
    "Year",
    "Area_Ha",
    "Production_Tonnes",
    "Yield_Kg_Ha"
]

print("Shape:", df_icar.shape)

print("\nColumns:")
print(df_icar.columns.tolist())

print("\nFirst 5 rows:")
display(df_icar.head())

print("\nData types:")
print(df_icar.dtypes)

print("\nMissing values:")
print(df_icar.isnull().sum())

print("\nDuplicate rows:", df_icar.duplicated().sum())

Shape: (27, 4)

Columns:
['Year', 'Area_Ha', 'Production_Tonnes', 'Yield_Kg_Ha']

First 5 rows:

   Year      Area_Ha  Production_Tonnes  Yield_Kg_Ha
0  2023  47828289.10        137824576.0       2882.0
1  2022  47831997.65        135755160.3       2838.0
2  2021  46278675.43        129471418.2       2798.0
3  2020  45768687.00        124368315.9       2717.0
4  2019  43662297.10        118870319.3       2722.0

Data types:
Year                   int64
Area_Ha              float64
Production_Tonnes    float64
Yield_Kg_Ha          float64
dtype: object

Missing values:
Year                 0
Area_Ha              0
Production_Tonnes    0
Yield_Kg_Ha          0
dtype: int64

Duplicate rows: 0

In [6]:
# ==========================================
# Historical Rice - Excel file inspection
# ==========================================

historical_files = list(HISTORICAL_DIR.rglob("*.xlsx"))

print("Total Excel files:", len(historical_files))

historical_summary = []

for file in historical_files:
    try:
        excel_file = pd.ExcelFile(file)

        historical_summary.append({
            "file": file.name,
            "folder": file.parent.name,
            "sheets": len(excel_file.sheet_names),
            "sheet_names": ", ".join(excel_file.sheet_names)
        })

    except Exception as e:
        historical_summary.append({
            "file": file.name,
            "folder": file.parent.name,
            "sheets": "ERROR",
            "sheet_names": str(e)
        })

historical_summary_df = pd.DataFrame(historical_summary)

print("\nHistorical Rice Summary:")
display(historical_summary_df.head(20))

Total Excel files: 93

Historical Rice Summary:

,file,folder,sheets,sheet_names
0,IND_RI_AKO_1977.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
1,IND_RI_AKO_1978.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
2,IND_RI_AKO_1979.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
3,IND_RI_JAB_1971.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
4,IND_RI_JAB_1972.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
5,IND_RI_JAB_1974.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
6,IND_RI_JAB_1975.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
7,IND_RI_JAB_1976.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
8,IND_RI_JAB_1980.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
9,IND_RI_JAB_1981.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
10,IND_RI_JAB_1986.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
11,IND_RI_JAB_1987.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
12,IND_RI_JAB_1988.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
13,IND_RI_JAB_1989.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
14,IND_RI_JAB_1990.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
15,IND_RI_JAB_1991.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
16,IND_RI_JAB_1994.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
17,IND_RI_JAB_2001.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
18,IND_RI_JAB_2002.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."
19,IND_RI_JAB_2003.xlsx,Central_India_Region,4,"Timeseries, Weather data, Treatments, Timeline..."

In [7]:
# ==========================================
# Historical Rice file information
# ==========================================

historical_info = []

for file in historical_files:
    size_kb = file.stat().st_size / 1024

    historical_info.append({
        "file": file.name,
        "region": file.parent.name,
        "size_kb": round(size_kb, 2)
    })

historical_info_df = pd.DataFrame(historical_info)

display(
    historical_info_df
    .sort_values("size_kb", ascending=False)
    .head(20)
)

                    file                 region  size_kb
17  IND_RI_JAB_2001.xlsx   Central_India_Region   267.63
1   IND_RI_AKO_1978.xlsx   Central_India_Region    57.32
65  IND_RI_MEE_2021.xlsx  Gangetic_Plain_Region    48.27
66  IND_RI_MEE_2022.xlsx  Gangetic_Plain_Region    48.18
79  IND_RI_NAD_1999.xlsx  Gangetic_Plain_Region    47.89
78  IND_RI_NAD_1998.xlsx  Gangetic_Plain_Region    47.86
37  IND_RI_RAN_2019.xlsx   Central_India_Region    47.52
86  IND_RI_PAN_2010.xlsx  Gangetic_Plain_Region    46.40
74  IND_RI_NAD_1989.xlsx  Gangetic_Plain_Region    45.92
2   IND_RI_AKO_1979.xlsx   Central_India_Region    44.38
30  IND_RI_RAI_2012.xlsx   Central_India_Region    44.25
61  IND_RI_KAU_1993.xlsx  Gangetic_Plain_Region    43.69
62  IND_RI_KAU_1994.xlsx  Gangetic_Plain_Region    43.66
57  IND_RI_KAU_1980.xlsx  Gangetic_Plain_Region    43.32
53  IND_RI_KAR_2004.xlsx  Gangetic_Plain_Region    43.18
71  IND_RI_NAD_1976.xlsx  Gangetic_Plain_Region    42.96
58  IND_RI_KAU_1983.xlsx  Gangetic_Plain_Region    42.90
59  IND_RI_KAU_1984.xlsx  Gangetic_Plain_Region    42.86
44  IND_RI_VAD_2016.xlsx   Central_India_Region    42.53
45  IND_RI_VAD_2017.xlsx   Central_India_Region    42.47

In [8]:
# ==========================================
# Inspect first Historical Rice Excel file
# ==========================================

first_historical_file = historical_files[0]

print("File:", first_historical_file.name)
print("Region:", first_historical_file.parent.name)

excel_file = pd.ExcelFile(first_historical_file)

print("\nSheets:")
print(excel_file.sheet_names)

for sheet in excel_file.sheet_names:
    df = pd.read_excel(first_historical_file, sheet_name=sheet)

    print("\n" + "=" * 60)
    print("Sheet:", sheet)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())

    print("\nFirst 5 rows:")
    display(df.head())

    print("\nMissing values:")
    display(df.isnull().sum())

File: IND_RI_AKO_1977.xlsx
Region: Central_India_Region

Sheets:
['Timeseries', 'Weather data', 'Treatments', 'Timeline field activities']

============================================================
Sheet: Timeseries
Shape: (5, 238)
Columns: ['Event', 'Serial number []', 'Country []', 'Journal/report title []', 'Author(s) []', 'Uniform resource locator/link to reference []', 'Journal/report publisher []', 'Year []', 'Location []', 'Lat [ºN]', 'Lon [ºE]', 'Season []', 'Crop type []', 'Species []', 'DATE/TIME []//*of growing season', 'Day of the year []', 'Standard meteorological week []', ' Sand, Coarse [%]', 'Sand, fine [%]', 'Silt [%]', 'Clay [%]', 'Calcium carbonate [%]', 'pH, soil []', 'Conductivity, electrical [mS/cm]', 'Organic carbon, soil [%]', 'Nitrogen, plant-available [kg/ha]', 'Phosphorus, plant-available [kg/ha]', 'Potassium, plant-available [kg/ha]', 'Plant, height [cm]//*Pusa-33', 'Plant, height [cm]//*Tella-Hamsa', 'Plant, height [cm]//*Nagpur-22', 'Plant, height [cm]//*Tuljapur-l', 'Plant, height [cm]//*Ganga sagar', 'Plant, height [cm]//*Drilling(Hand sowing)', 'Plant, height [cm]//*Transplanting', 'Shoot [#/hill]//*Pusa-33', 'Shoot [#/hill]//*Tella-Hamsa', 'Shoot [#/hill]//*Nagpur-22', 'Shoot [#/hill]//*Tuljapur-l', 'Shoot [#/hill]//*Ganga sagar', 'Shoot [#/hill]//*Drilling(Hand sowing)', 'Shoot [#/hill]//*Transplanting', 'Plant, population [#/hill]//*Pusa-33', 'Plant, population [#/hill]//*Tella-Hamsa', 'Plant, population [#/hill]//*Nagpur-22', 'Plant, population [#/hill]//*Tuljapur-l', 'Plant, population [#/hill]//*Ganga sagar', 'Plant, population [#/hill]//*Drilling(Hand sowing)', 'Plant, population [#/hill]//*Transplanting', 'Plant, population [#/hill]//*no puddling;Treatment:D0', 'Plant, dry matter [g/hill]//*Pusa-33', 'Plant, dry matter [g/hill]//*Tella-Hamsa', 'Plant, dry matter [g/hill]//*Nagpur-22', 'Plant, dry matter [g/hill]//*Tuljapur-l', 'Plant, dry matter [g/hill]//*Ganga sagar', 'Plant, dry matter [g/hill]//*Drilling(Hand sowing)', 'Plant, dry matter  [g/hill]//*Transplanting', 'Panicle [#/hill]//*Pusa-33', 'Panicle [#/hill]//*Tella-Hamsa', 'Panicle [#/hill]//*Nagpur-22', 'Panicle [#/hill]//*Tuljapur-l', 'Panicle [#/hill]//*Ganga sagar', 'Panicle [#/hill]//*Drilling(Hand sowing)', 'Panicle [#/hill]//*Transplanting', 'Panicle, length [cm]//*Pusa-33', 'Panicle, length [cm]//*Tella-Hamsa', 'Panicle, length [cm]//*Nagpur-22', 'Panicle, length [cm]//*Tuljapur-l', 'Panicle, length [cm]//*Ganga sagar', 'Panicle, length [cm]//*Drilling(Hand sowing)', 'Panicle, length [cm]//*Transplanting', 'Branches, rachis [cm]//*Pusa-33', 'Branches, rachis [cm]//*Tella-Hamsa', 'Branches, rachis [cm]//*Nagpur-22', 'Branches, rachis [cm]//*Tuljapur-l', 'Branches, rachis [cm]//*Ganga sagar', 'Branches, rachis [cm]//*Drilling(Hand sowing)', 'Branches, rachis [cm]//*Transplanting', 'Grain [#/hill]//*Pusa-33', 'Grain [#/hill]//*Tella-Hamsa', 'Grain [#/hill]//*Nagpur-22', 'Grain [#/hill]//*Tuljapur-l', 'Grain [#/hill]//*Ganga sagar', 'Grain [#/hill]//*Drilling(Hand sowing)', 'Grain [#/hill]//*Transplanting', 'Panicle, weight [g]//*Pusa-33', 'Panicle, weight [g]//*Tella-Hamsa', 'Panicle, weight [g]//*Nagpur-22', 'Panicle, weight [g]//*Tuljapur-l', 'Panicle, weight [g]//*Ganga sagar', 'Panicle, weight [g]//*Drilling(Hand sowing)', 'Panicle, weight [g]//*Transplanting', 'Sterility [%]//*Pusa-33', 'Sterility [%]//*Tella-Hamsa', 'Sterility [%]//*Nagpur-22', 'Sterility [%]//*Tuljapur-l', 'Sterility [%]//*Ganga sagar', 'Sterility [%]//*Drilling(Hand sowing)', 'Sterility [%]//*Transplanting', '1000-grain weight [g]//*Pusa-33', '1000-grain weight [g]//*Tella-Hamsa', '1000-grain weight [g]//*Nagpur-22', '1000-grain weight [g]//*Tuljapur-l', '1000-grain weight [g]//*Ganga sagar', '1000-grain weight [g]//*Drilling(Hand sowing)', '1000-grain weight [g]//*Transplanting', 'Grain yield [q/ha]//*Pusa-33', 'Grain yield [q/ha]//*Tella-Hamsa', 'Grain yield [q/ha]//*Nagpur-22', 'Grain yield [q/ha]//*Tuljapur-l', 'Grain yield [q/ha]//*Ganga sagar', 'Grain yield [q/ha]//*Drilling(Hand sowing)', 'Straw yield [q/ha]//*Pusa-33', 'Straw yield [q/ha]//*Tella-Hamsa', 'Straw yield [q/ha]//*Nagpur-22', 'Straw yield [q/ha]//*Tuljapur-l', 'Straw yield [q/ha]//*Ganga sagar', 'Straw yield [q/ha]//*Drilling(Hand sowing)', 'Straw yield [q/ha]//*Transplanting', 'Grain, straw, ratio//*Pusa-33', 'Grain, straw, ratio//*Tella-Hamsa', 'Grain, straw, ratio//*Nagpur-22', 'Grain, straw, ratio//*Tuljapur-l', 'Grain, straw, ratio//*Ganga sagar', 'Grain, straw, ratio//*Drilling(Hand sowing)', 'Grain, straw, ratio//*Transplanting', 'Hulling [%]//*Pusa-33', 'Hulling [%]//*Tella-Hamsa', 'Hulling [%]//*Nagpur-22', 'Hulling [%]//*Tuljapur-l', 'Hulling [%]//*Ganga sagar', 'Hulling [%]//*Drilling(Hand sowing)', 'Hulling [%]//*Transplanting', 'Nitrogen, grain [%]//*Pusa-33', 'Nitrogen, grain [%]//*Tella-Hamsa', 'Nitrogen, grain [%]//*Nagpur-22', 'Nitrogen, grain [%]//*Tuljapur-l', 'Nitrogen, grain [%]//*Ganga sagar', 'Nitrogen, grain [%]//*Drilling(Hand sowing)', 'Nitrogen, grain [%]//*Transplanting', 'Nitrogen, straw  [%]//*Pusa-33', 'Nitrogen, straw  [%]//*Tella-Hamsa', 'Nitrogen, straw  [%]//*Nagpur-22', 'Nitrogen, straw  [%]//*Tuljapur-l', 'Nitrogen, straw  [%]//*Ganga sagar', 'Nitrogen, straw  [%]//*Drilling(Hand sowing)', 'Nitrogen, straw  [%]//*Transplanting', 'Nitrogen, uptake, grain [kg/ha]//*Pusa-33', 'Nitrogen, uptake, grain [kg/ha]//*Tella-Hamsa', 'Nitrogen, uptake, grain [kg/ha]//*Nagpur-22', 'Nitrogen, uptake, grain [kg/ha]//*Tuljapur-l', 'Nitrogen, uptake, grain [kg/ha]//*Ganga sagar', 'Nitrogen, uptake, grain [kg/ha]//*Drilling(Hand sowing)', 'Nitrogen, uptake, grain [kg/ha]//*Transplanting', 'Nitrogen, uptake, straw [kg/ha]//*Pusa-33', 'Nitrogen, uptake, straw [kg/ha]//*Tella-Hamsa', 'Nitrogen, uptake, straw [kg/ha]//*Nagpur-22', 'Nitrogen, uptake, straw [kg/ha]//*Tuljapur-l', 'Nitrogen, uptake, straw  [kg/ha]//*Ganga sagar', 'Nitrogen, uptake, straw  [kg/ha]//*Drilling(Hand sowing)', 'Nitrogen, uptake, straw  [kg/ha]//*Transplanting', 'Nitrogen, uptake,total [kg/ha]//*Pusa-33', 'Nitrogen, uptake,total [kg/ha]//*Tella-Hamsa', 'Nitrogen, uptake,total [kg/ha]//*Nagpur-22', 'Nitrogen, uptake,total [kg/ha]//*Tuljapur-l', 'Nitrogen, uptake,total [kg/ha]//*Ganga sagar', 'Nitrogen, uptake,total [kg/ha]//*Drilling(Hand sowing)', 'Nitrogen, uptake,total [kg/ha]//*Transplanting', 'Phosphorus, grain [%]//*Pusa-33', 'Phosphorus, grain  [%]//*Tella-Hamsa', 'Phosphorus, grain  [%]//*Nagpur-22', 'Phosphorus, grain  [%]//*Tuljapur-l', 'Phosphorus, grain  [%]//*Ganga sagar', 'Phosphorus, grain  [%]//*Drilling(Hand sowing)', 'Phosphorus, grain  [%]//*Transplanting', 'Phosphorus, straw  [%]//*Pusa-33', 'Phosphorus, straw  [%]//*Tella-Hamsa', 'Phosphorus, straw  [%]//*Nagpur-22', 'Phosphorus, straw  [%]//*Tuljapur-l', 'Phosphorus, straw  [%]//*Ganga sagar', 'Phosphorus, straw  [%]//*Drilling(Hand sowing)', 'Phosphorus, straw  [%]//*Transplanting', 'Phosphorus, uptake, grain [kg/ha]//*Pusa-33', 'Phosphorus, uptake, grain [kg/ha]//*Tella-Hamsa', 'Phosphorus, uptake, grain [kg/ha]//*Nagpur-22', 'Phosphorus, uptake, grain [kg/ha]//*Tuljapur-l', 'Phosphorus, uptake, grain [kg/ha]//*Ganga sagar', 'Phosphorus, uptake, grain [kg/ha]//*Drilling(Hand sowing)', 'Phosphorus, uptake, grain [kg/ha]//*Transplanting', 'Phosphorus, uptake, straw [kg/ha]//*Pusa-33', 'Phosphorus, uptake, straw [kg/ha]//*Tella-Hamsa', 'Phosphorus, uptake, straw [kg/ha]//*Nagpur-22', 'Phosphorus, uptake, straw [kg/ha]//*Tuljapur-l', 'Phosphorus, uptake, straw  [kg/ha]//*Ganga sagar', 'Phosphorus, uptake, straw  [kg/ha]//*Drilling(Hand sowing)', 'Phosphorus, uptake, straw  [kg/ha]//*Transplanting', 'Phosphorus, uptake, total [kg/ha]//*Pusa-33', 'Phosphorus, uptake, total [kg/ha]//*Tella-Hamsa', 'Phosphorus, uptake, total [kg/ha]//*Nagpur-22', 'Phosphorus, uptake, total [kg/ha]//*Tuljapur-l', 'Phosphorus, uptake, total [kg/ha]//*Ganga sagar', 'Phosphorus, uptake, total [kg/ha]//*Drilling(Hand sowing)', 'Phosphorus, uptake, total [kg/ha]//*Transplanting', 'Potassium, grain [%]//*Pusa-33', 'Potassium, grain  [%]//*Tella-Hamsa', 'Potassium, grain  [%]//*Nagpur-22', 'Potassium, grain  [%]//*Tuljapur-l', 'Potassium, grain  [%]//*Ganga sagar', 'Potassium, grain  [%]//*Drilling(Hand sowing)', 'Potassium, grain  [%]//*Transplanting', 'Potassium, straw  [%]//*Pusa-33', 'Potassium, straw  [%]//*Tella-Hamsa', 'Potassium, straw  [%]//*Nagpur-22', 'Potassium, straw  [%]//*Tuljapur-l', 'Potassium, straw  [%]//*Ganga sagar', 'Potassium, straw  [%]//*Drilling(Hand sowing)', 'Potassium, straw  [%]//*Transplanting', 'Potassium, uptake, grain [kg/ha]//*Pusa-33', 'Potassium, uptake, grain [kg/ha]//*Tella-Hamsa', 'Potassium, uptake, grain [kg/ha]//*Nagpur-22', 'Potassium, uptake, grain [kg/ha]//*Tuljapur-l', 'Potassium, uptake, grain [kg/ha]//*Ganga sagar', 'Potassium, uptake, grain [kg/ha]//*Drilling(Hand sowing)', 'Potassium, uptake,grain [kg/ha]//*Transplanting', 'Potassium, uptake, straw [kg/ha]//*Pusa-33', 'Potassium, uptake, straw [kg/ha]//*Tella-Hamsa', 'Potassium, uptake, straw [kg/ha]//*Nagpur-22', 'Potassium, uptake, straw [kg/ha]//*Tuljapur-l', 'Potassium, uptake, straw  [kg/ha]//*Ganga sagar', 'Potassium, uptake, straw  [kg/ha]//*Drilling(Hand sowing)', 'Potassium, uptake, straw  [kg/ha]//*Transplanting', 'Potassium, uptake, total [kg/ha]//*Pusa-33', 'Potassium, uptake, total [kg/ha]//*Tella-Hamsa', 'Potassium, uptake, total [kg/ha]//*Nagpur-22', 'Potassium, uptake, total [kg/ha]//*Tuljapur-l', 'Potassium, uptake, total [kg/ha]//*Ganga sagar', 'Potassium, uptake, total [kg/ha]//*Drilling(Hand sowing)', 'Potassium, uptake, total [kg/ha]//*Transplanting']

First 5 rows:

,Event,Serial number [],Country [],Journal/report title [],Author(s) [],Uniform resource locator/link to reference [],Journal/report publisher [],Year [],Location [],Lat [ºN],...,"Potassium, uptake, straw [kg/ha]//*Ganga sagar","Potassium, uptake, straw [kg/ha]//*Drilling(Hand sowing)","Potassium, uptake, straw [kg/ha]//*Transplanting","Potassium, uptake, total [kg/ha]//*Pusa-33","Potassium, uptake, total [kg/ha]//*Tella-Hamsa","Potassium, uptake, total [kg/ha]//*Nagpur-22","Potassium, uptake, total [kg/ha]//*Tuljapur-l","Potassium, uptake, total [kg/ha]//*Ganga sagar","Potassium, uptake, total [kg/ha]//*Drilling(Hand sowing)","Potassium, uptake, total [kg/ha]//*Transplanting"
0,IND_RI_AKO_1977,0 DAS,India,INVESTIGATIONS ON SOME AGRONOMIC ASPECTS OF RI...,"THDSAR, VIJAY RAMCHANDRA",http://krishikosh.egranth.ac.in/handle/1/58101...,"Dr. Panjabrao Deshmukh Krishi Vidyapeeth, Akol...",23-06-1982,Akola,20.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IND_RI_AKO_1977,60 DAS,India,INVESTIGATIONS ON SOME AGRONOMIC ASPECTS OF RI...,"THDSAR, VIJAY RAMCHANDRA",http://krishikosh.egranth.ac.in/handle/1/58101...,"Dr. Panjabrao Deshmukh Krishi Vidyapeeth, Akol...",23-06-1982,Akola,20.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IND_RI_AKO_1977,75 DAS,India,INVESTIGATIONS ON SOME AGRONOMIC ASPECTS OF RI...,"THDSAR, VIJAY RAMCHANDRA",http://krishikosh.egranth.ac.in/handle/1/58101...,"Dr. Panjabrao Deshmukh Krishi Vidyapeeth, Akol...",23-06-1982,Akola,20.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IND_RI_AKO_1977,90 DAS,India,INVESTIGATIONS ON SOME AGRONOMIC ASPECTS OF RI...,"THDSAR, VIJAY RAMCHANDRA",http://krishikosh.egranth.ac.in/handle/1/58101...,"Dr. Panjabrao Deshmukh Krishi Vidyapeeth, Akol...",23-06-1982,Akola,20.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IND_RI_AKO_1977,AT HARVEST,India,INVESTIGATIONS ON SOME AGRONOMIC ASPECTS OF RI...,"THDSAR, VIJAY RAMCHANDRA",http://krishikosh.egranth.ac.in/handle/1/58101...,"Dr. Panjabrao Deshmukh Krishi Vidyapeeth, Akol...",23-06-1982,Akola,20.71,...,58.08,45.53,49.6,43.13,48.09,66.27,71.93,71.88,57.1,63.12

Missing values:

Event                                                       0
Serial number []                                            0
Country []                                                  0
Journal/report title []                                     0
Author(s) []                                                0
                                                           ..
Potassium, uptake, total [kg/ha]//*Nagpur-22                4
Potassium, uptake, total [kg/ha]//*Tuljapur-l               4
Potassium, uptake, total [kg/ha]//*Ganga sagar              4
Potassium, uptake, total [kg/ha]//*Drilling(Hand sowing)    4
Potassium, uptake, total [kg/ha]//*Transplanting            4
Length: 238, dtype: int64

============================================================
Sheet: Weather data
Shape: (22, 11)
Columns: ['Location []', 'Lat [ºN]', 'Lon [ºE]', 'Standard meteorological week []', 'Temperature, maximum, mean [°C]', 'Temperature, minimum, mean [°C]', 'Relative humidity, minimum [%]', 'Relative humidity, maximum [%]', 'Rainfall [mm]', 'Rainy (Days)', 'Sunshine [hour/day]']

First 5 rows:

,Location [],Lat [ºN],Lon [ºE],Standard meteorological week [],"Temperature, maximum, mean [°C]","Temperature, minimum, mean [°C]","Relative humidity, minimum [%]","Relative humidity, maximum [%]",Rainfall [mm],Rainy (Days),Sunshine [hour/day]
0,Akola,20.71,77.05,26,30.9,23.1,68,87,96.5,6.5,3.0
1,Akola,20.71,77.05,27,31.5,23.0,65,86,30.0,2.0,3.8
2,Akola,20.71,77.05,28,32.4,23.6,61,84,4.6,1.0,5.4
3,Akola,20.71,77.05,29,34.5,23.7,53,96,43.0,2.0,7.3
4,Akola,20.71,77.05,30,30.5,22.7,81,92,159.6,7.0,2.5

Missing values:

Location []                        0
Lat [ºN]                           0
Lon [ºE]                           0
Standard meteorological week []    0
Temperature, maximum, mean [°C]    0
Temperature, minimum, mean [°C]    0
Relative humidity, minimum [%]     0
Relative humidity, maximum [%]     0
Rainfall [mm]                      0
Rainy (Days)                       0
Sunshine [hour/day]                0
dtype: int64

============================================================
Sheet: Treatments
Shape: (22, 2)
Columns: ['Treatments', 'Symbol']

First 5 rows:

                                          Treatments Symbol
0  A) 1. Irrigation at 40 mm cumulative pan evapo...     I1
1               Irrigation at 30 mm cumulative (CPE]     I2
2               Irrigation at 20 mm cumulative (CPE]     I3
3                                        No puddling     D0
4                           Puddling upto 5 cm depth     D1

Missing values:

Treatments    0
Symbol        1
dtype: int64

============================================================
Sheet: Timeline field activities
Shape: (23, 5)
Columns: ['Sl.No', 'Agricultural operation', 'Crop', 'Rice establishment methods', 'Date of operation']

First 5 rows:

,Sl.No,Agricultural operation,Crop,Rice establishment methods,Date of operation
0,1,Nursery sowing,Rice,Transplanted rice (TPR),28-06-1977
1,2,Transplanting,Rice,Transplanted rice (TPR),25-07-1977
2,3,Fertilizer application,Rice,Transplanted rice (TPR),NaN
3,4,Basal dose -P1,Rice,Transplanted rice (TPR),28-06-1977
4,5,Basal dose -P2,Rice,Transplanted rice (TPR),25-07-1977

Missing values:

Sl.No                         0
Agricultural operation        0
Crop                          0
Rice establishment methods    0
Date of operation             2
dtype: int64

In [9]:
# ==========================================
# Historical Rice - All sheets & columns
# ==========================================

all_sheets_info = []

for file in historical_files:

    try:
        excel_file = pd.ExcelFile(file)

        for sheet in excel_file.sheet_names:

            df = pd.read_excel(file, sheet_name=sheet)

            all_sheets_info.append({
                "file": file.name,
                "region": file.parent.name,
                "sheet": sheet,
                "rows": df.shape[0],
                "columns_count": df.shape[1],
                "columns": " | ".join(map(str, df.columns))
            })

    except Exception as e:

        all_sheets_info.append({
            "file": file.name,
            "region": file.parent.name,
            "sheet": "ERROR",
            "rows": 0,
            "columns_count": 0,
            "columns": str(e)
        })


all_sheets_df = pd.DataFrame(all_sheets_info)

print("Total sheets inspected:", len(all_sheets_df))

display(all_sheets_df)

Total sheets inspected: 373

,file,region,sheet,rows,columns_count,columns
0,IND_RI_AKO_1977.xlsx,Central_India_Region,Timeseries,5,238,Event | Serial number [] | Country [] | Journa...
1,IND_RI_AKO_1977.xlsx,Central_India_Region,Weather data,22,11,Location [] | Lat [ºN] | Lon [ºE] | Standard m...
2,IND_RI_AKO_1977.xlsx,Central_India_Region,Treatments,22,2,Treatments | Symbol
3,IND_RI_AKO_1977.xlsx,Central_India_Region,Timeline field activities,23,5,Sl.No | Agricultural operation | Crop | Rice e...
4,IND_RI_AKO_1978.xlsx,Central_India_Region,Timeseries,14,506,Event | Serial number [] | Country [] | Journa...
...,...,...,...,...,...,...
368,IND_RI_PAN_2018.xlsx,Gangetic_Plain_Region,Timeline field activities,7,3,Sl.No | Agricultural operation | Date of opera...
369,IND_RI_PAN_2019.xlsx,Gangetic_Plain_Region,Timeseries,5,322,Event | Serial number [] | Country [] | Journa...
370,IND_RI_PAN_2019.xlsx,Gangetic_Plain_Region,Weather data,20,13,Location [] | Lat [ºN] | Lon [ºE] | Standard m...
371,IND_RI_PAN_2019.xlsx,Gangetic_Plain_Region,Treatments,19,2,Treatments | Symbol
372,IND_RI_PAN_2019.xlsx,Gangetic_Plain_Region,Timeline field activities,27,5,Sl.No | Agricultural operation | Crop | Rice e...

In [10]:
# ==========================================
# Unique sheet types in Historical Rice
# ==========================================

sheet_summary = (
    all_sheets_df
    .groupby("sheet")
    .agg(
        total_files=("file", "count"),
        total_rows=("rows", "sum"),
        min_rows=("rows", "min"),
        max_rows=("rows", "max")
    )
    .reset_index()
    .sort_values("total_files", ascending=False)
)

display(sheet_summary)

                       sheet  total_files  total_rows  min_rows  max_rows
1  Timeline field activities           93        1210         2       108
3                 Treatments           93         876         3        34
2                 Timeseries           93         877         2        80
4               Weather data           93        1539         1        28
0                     Sheet1            1           0         0         0

In [11]:
# ==========================================
# Columns available in each sheet type
# ==========================================

for sheet_name in all_sheets_df["sheet"].dropna().unique():

    print("\n" + "=" * 80)
    print("SHEET:", sheet_name)
    print("=" * 80)

    subset = all_sheets_df[
        all_sheets_df["sheet"] == sheet_name
    ]

    unique_columns = subset["columns"].dropna().unique()

    print("Different column structures:", len(unique_columns))

    for i, columns in enumerate(unique_columns, start=1):
        print(f"\nStructure {i}:")
        print(columns)

================================================================================
SHEET: Timeseries
================================================================================
Different column structures: 76

Structure 1:
Event | Serial number [] | Country [] | Journal/report title [] | Author(s) [] | Uniform resource locator/link to reference [] | Journal/report publisher [] | Year [] | Location [] | Lat [ºN] | Lon [ºE] | Season [] | Crop type [] | Species [] | DATE/TIME []//*of growing season | Day of the year [] | Standard meteorological week [] |  Sand, Coarse [%] | Sand, fine [%] | Silt [%] | Clay [%] | Calcium carbonate [%] | pH, soil [] | Conductivity, electrical [mS/cm] | Organic carbon, soil [%] | Nitrogen, plant-available [kg/ha] | Phosphorus, plant-available [kg/ha] | Potassium, plant-available [kg/ha] | Plant, height [cm]//*Pusa-33 | Plant, height [cm]//*Tella-Hamsa | Plant, height [cm]//*Nagpur-22 | Plant, height [cm]//*Tuljapur-l | Plant, height [cm]//*Ganga sagar | Plant, height [cm]//*Drilling(Hand sowing) | Plant, height [cm]//*Transplanting | Shoot [#/hill]//*Pusa-33 | Shoot [#/hill]//*Tella-Hamsa | Shoot [#/hill]//*Nagpur-22 | Shoot [#/hill]//*Tuljapur-l | Shoot [#/hill]//*Ganga sagar | Shoot [#/hill]//*Drilling(Hand sowing) | Shoot [#/hill]//*Transplanting | Plant, population [#/hill]//*Pusa-33 | Plant, population [#/hill]//*Tella-Hamsa | Plant, population [#/hill]//*Nagpur-22 | Plant, population [#/hill]//*Tuljapur-l | Plant, population [#/hill]//*Ganga sagar | Plant, population [#/hill]//*Drilling(Hand sowing) | Plant, population [#/hill]//*Transplanting | Plant, population [#/hill]//*no puddling;Treatment:D0 | Plant, dry matter [g/hill]//*Pusa-33 | Plant, dry matter [g/hill]//*Tella-Hamsa | Plant, dry matter [g/hill]//*Nagpur-22 | Plant, dry matter [g/hill]//*Tuljapur-l | Plant, dry matter [g/hill]//*Ganga sagar | Plant, dry matter [g/hill]//*Drilling(Hand sowing) | Plant, dry matter  [g/hill]//*Transplanting | Panicle [#/hill]//*Pusa-33 | Panicle [#/hill]//*Tella-Hamsa | Panicle [#/hill]//*Nagpur-22 | Panicle [#/hill]//*Tuljapur-l | Panicle [#/hill]//*Ganga sagar | Panicle [#/hill]//*Drilling(Hand sowing) | Panicle [#/hill]//*Transplanting | Panicle, length [cm]//*Pusa-33 | Panicle, length [cm]//*Tella-Hamsa | Panicle, length [cm]//*Nagpur-22 | Panicle, length [cm]//*Tuljapur-l | Panicle, length [cm]//*Ganga sagar | Panicle, length [cm]//*Drilling(Hand sowing) | Panicle, length [cm]//*Transplanting | Branches, rachis [cm]//*Pusa-33 | Branches, rachis [cm]//*Tella-Hamsa | Branches, rachis [cm]//*Nagpur-22 | Branches, rachis [cm]//*Tuljapur-l | Branches, rachis [cm]//*Ganga sagar | Branches, rachis [cm]//*Drilling(Hand sowing) | Branches, rachis [cm]//*Transplanting | Grain [#/hill]//*Pusa-33 | Grain [#/hill]//*Tella-Hamsa | Grain [#/hill]//*Nagpur-22 | Grain [#/hill]//*Tuljapur-l | Grain [#/hill]//*Ganga sagar | Grain [#/hill]//*Drilling(Hand sowing) | Grain [#/hill]//*Transplanting | Panicle, weight [g]//*Pusa-33 | Panicle, weight [g]//*Tella-Hamsa | Panicle, weight [g]//*Nagpur-22 | Panicle, weight [g]//*Tuljapur-l | Panicle, weight [g]//*Ganga sagar | Panicle, weight [g]//*Drilling(Hand sowing) | Panicle, weight [g]//*Transplanting | Sterility [%]//*Pusa-33 | Sterility [%]//*Tella-Hamsa | Sterility [%]//*Nagpur-22 | Sterility [%]//*Tuljapur-l | Sterility [%]//*Ganga sagar | Sterility [%]//*Drilling(Hand sowing) | Sterility [%]//*Transplanting | 1000-grain weight [g]//*Pusa-33 | 1000-grain weight [g]//*Tella-Hamsa | 1000-grain weight [g]//*Nagpur-22 | 1000-grain weight [g]//*Tuljapur-l | 1000-grain weight [g]//*Ganga sagar | 1000-grain weight [g]//*Drilling(Hand sowing) | 1000-grain weight [g]//*Transplanting | Grain yield [q/ha]//*Pusa-33 | Grain yield [q/ha]//*Tella-Hamsa | Grain yield [q/ha]//*Nagpur-22 | Grain yield [q/ha]//*Tuljapur-l | Grain yield [q/ha]//*Ganga sagar | Grain yield [q/ha]//*Drilling(Hand sowing) | Straw yield [q/ha]//*Pusa-33 | Straw yield [q/ha]//*Tella-Hamsa | Straw yield [q/ha]//*Nagpur-22 | Straw yield [q/ha]//*Tuljapur-l | Straw yield [q/ha]//*Ganga sagar | Straw yield [q/ha]//*Drilling(Hand sowing) | Straw yield [q/ha]//*Transplanting | Grain, straw, ratio//*Pusa-33 | Grain, straw, ratio//*Tella-Hamsa | Grain, straw, ratio//*Nagpur-22 | Grain, straw, ratio//*Tuljapur-l | Grain, straw, ratio//*Ganga sagar | Grain, straw, ratio//*Drilling(Hand sowing) | Grain, straw, ratio//*Transplanting | Hulling [%]//*Pusa-33 | Hulling [%]//*Tella-Hamsa | Hulling [%]//*Nagpur-22 | Hulling [%]//*Tuljapur-l | Hulling [%]//*Ganga sagar | Hulling [%]//*Drilling(Hand sowing) | Hulling [%]//*Transplanting | Nitrogen, grain [%]//*Pusa-33 | Nitrogen, grain [%]//*Tella-Hamsa | Nitrogen, grain [%]//*Nagpur-22 | Nitrogen, grain [%]//*Tuljapur-l | Nitrogen, grain [%]//*Ganga sagar | Nitrogen, grain [%]//*Drilling(Hand sowing) | Nitrogen, grain [%]//*Transplanting | Nitrogen, straw  [%]//*Pusa-33 | Nitrogen, straw  [%]//*Tella-Hamsa | Nitrogen, straw  [%]//*Nagpur-22 | Nitrogen, straw  [%]//*Tuljapur-l | Nitrogen, straw  [%]//*Ganga sagar | Nitrogen, straw  [%]//*Drilling(Hand sowing) | Nitrogen, straw  [%]//*Transplanting | Nitrogen, uptake, grain [kg/ha]//*Pusa-33 | Nitrogen, uptake, grain [kg/ha]//*Tella-Hamsa | Nitrogen, uptake, grain [kg/ha]//*Nagpur-22 | Nitrogen, uptake, grain [kg/ha]//*Tuljapur-l | Nitrogen, uptake, grain [kg/ha]//*Ganga sagar | Nitrogen, uptake, grain [kg/ha]//*Drilling(Hand sowing) | Nitrogen, uptake, grain [kg/ha]//*Transplanting | Nitrogen, uptake, straw [kg/ha]//*Pusa-33 | Nitrogen, uptake, straw [kg/ha]//*Tella-Hamsa | Nitrogen, uptake, straw [kg/ha]//*Nagpur-22 | Nitrogen, uptake, straw [kg/ha]//*Tuljapur-l | Nitrogen, uptake, straw  [kg/ha]//*Ganga sagar | Nitrogen, uptake, straw  [kg/ha]//*Drilling(Hand sowing) | Nitrogen, uptake, straw  [kg/ha]//*Transplanting | Nitrogen, uptake,total [kg/ha]//*Pusa-33 | Nitrogen, uptake,total [kg/ha]//*Tella-Hamsa | Nitrogen, uptake,total [kg/ha]//*Nagpur-22 | Nitrogen, uptake,total [kg/ha]//*Tuljapur-l | Nitrogen, uptake,total [kg/ha]//*Ganga sagar | Nitrogen, uptake,total [kg/ha]//*Drilling(Hand sowing) | Nitrogen, uptake,total [kg/ha]//*Transplanting | Phosphorus, grain [%]//*Pusa-33 | Phosphorus, grain  [%]//*Tella-Hamsa | Phosphorus, grain  [%]//*Nagpur-22 | Phosphorus, grain  [%]//*Tuljapur-l | Phosphorus, grain  [%]//*Ganga sagar | Phosphorus, grain  [%]//*Drilling(Hand sowing) | Phosphorus, grain  [%]//*Transplanting | Phosphorus, straw  [%]//*Pusa-33 | Phosphorus, straw  [%]//*Tella-Hamsa | Phosphorus, straw  [%]//*Nagpur-22 | Phosphorus, straw  [%]//*Tuljapur-l | Phosphorus, straw  [%]//*Ganga sagar | Phosphorus, straw  [%]//*Drilling(Hand sowing) | Phosphorus, straw  [%]//*Transplanting | Phosphorus, uptake, grain [kg/ha]//*Pusa-33 | Phosphorus, uptake, grain [kg/ha]//*Tella-Hamsa | Phosphorus, uptake, grain [kg/ha]//*Nagpur-22 | Phosphorus, uptake, grain [kg/ha]//*Tuljapur-l | Phosphorus, uptake, grain [kg/ha]//*Ganga sagar | Phosphorus, uptake, grain [kg/ha]//*Drilling(Hand sowing) | Phosphorus, uptake, grain [kg/ha]//*Transplanting | Phosphorus, uptake, straw [kg/ha]//*Pusa-33 | Phosphorus, uptake, straw [kg/ha]//*Tella-Hamsa | Phosphorus, uptake, straw [kg/ha]//*Nagpur-22 | Phosphorus, uptake, straw [kg/ha]//*Tuljapur-l | Phosphorus, uptake, straw  [kg/ha]//*Ganga sagar | Phosphorus, uptake, straw  [kg/ha]//*Drilling(Hand sowing) | Phosphorus, uptake, straw  [kg/ha]//*Transplanting | Phosphorus, uptake, total [kg/ha]//*Pusa-33 | Phosphorus, uptake, total [kg/ha]//*Tella-Hamsa | Phosphorus, uptake, total [kg/ha]//*Nagpur-22 | Phosphorus, uptake, total [kg/ha]//*Tuljapur-l | Phosphorus, uptake, total [kg/ha]//*Ganga sagar | Phosphorus, uptake, total [kg/ha]//*Drilling(Hand sowing) | Phosphorus, uptake, total [kg/ha]//*Transplanting | Potassium, grain [%]//*Pusa-33 | Potassium, grain  [%]//*Tella-Hamsa | Potassium, grain  [%]//*Nagpur-22 | Potassium, grain  [%]//*Tuljapur-l | Potassium, grain  [%]//*Ganga sagar | Potassium, grain  [%]//*Drilling(Hand sowing) | Potassium, grain  [%]//*Transplanting | Potassium, straw  [%]//*Pusa-33 | Potassium, straw  [%]//*Tella-Hamsa | Potassium, straw  [%]//*Nagpur-22 | Potassium, straw  [%]//*Tuljapur-l | Potassium, straw  [%]//*Ganga sagar | Potassium, straw  [%]//*Drilling(Hand sowing) | Potassium, straw  [%]//*Transplanting | Potassium, uptake, grain [kg/ha]//*Pusa-33 | Potassium, uptake, grain [kg/ha]//*Tella-Hamsa | Potassium, uptake, grain [kg/ha]//*Nagpur-22 | Potassium, uptake, grain [kg/ha]//*Tuljapur-l | Potassium, uptake, grain [kg/ha]//*Ganga sagar | Potassium, uptake, grain [kg/ha]//*Drilling(Hand sowing) | Potassium, uptake,grain [kg/ha]//*Transplanting | Potassium, uptake, straw [kg/ha]//*Pusa-33 | Potassium, uptake, straw [kg/ha]//*Tella-Hamsa | Potassium, uptake, straw [kg/ha]//*Nagpur-22 | Potassium, uptake, straw [kg/ha]//*Tuljapur-l | Potassium, uptake, straw  [kg/ha]//*Ganga sagar | Potassium, uptake, straw  [kg/ha]//*Drilling(Hand sowing) | Potassium, uptake, straw  [kg/ha]//*Transplanting | Potassium, uptake, total [kg/ha]//*Pusa-33 | Potassium, uptake, total [kg/ha]//*Tella-Hamsa | Potassium, uptake, total [kg/ha]//*Nagpur-22 | Potassium, uptake, total [kg/ha]//*Tuljapur-l | Potassium, uptake, total [kg/ha]//*Ganga sagar | Potassium, uptake, total [kg/ha]//*Drilling(Hand sowing) | Potassium, uptake, total [kg/ha]//*Transplanting

Structure 2:

In [12]:
# ==========================================
# Compact column summary for Historical Rice
# ==========================================

for sheet_name in ["Timeseries", "Weather data", "Treatments", "Timeline field activities"]:

    print("\n" + "=" * 80)
    print(f"SHEET: {sheet_name}")
    print("=" * 80)

    subset = all_sheets_df[
        all_sheets_df["sheet"] == sheet_name
    ]

    unique_columns = subset["columns"].dropna().unique()

    for i, columns in enumerate(unique_columns, start=1):
        print(f"\nStructure {i}:")
        print(columns)

================================================================================
SHEET: Timeseries
================================================================================

Structure 1:
Event | Serial number [] | Country [] | Journal/report title [] | Author(s) [] | Uniform resource locator/link to reference [] | Journal/report publisher [] | Year [] | Location [] | Lat [ºN] | Lon [ºE] | Season [] | Crop type [] | Species [] | DATE/TIME []//*of growing season | Day of the year [] | Standard meteorological week [] |  Sand, Coarse [%] | Sand, fine [%] | Silt [%] | Clay [%] | Calcium carbonate [%] | pH, soil [] | Conductivity, electrical [mS/cm] | Organic carbon, soil [%] | Nitrogen, plant-available [kg/ha] | Phosphorus, plant-available [kg/ha] | Potassium, plant-available [kg/ha] | Plant, height [cm]//*Pusa-33 | Plant, height [cm]//*Tella-Hamsa | Plant, height [cm]//*Nagpur-22 | Plant, height [cm]//*Tuljapur-l | Plant, height [cm]//*Ganga sagar | Plant, height [cm]//*Drilling(Hand sowing) | Plant, height [cm]//*Transplanting | Shoot [#/hill]//*Pusa-33 | Shoot [#/hill]//*Tella-Hamsa | Shoot [#/hill]//*Nagpur-22 | Shoot [#/hill]//*Tuljapur-l | Shoot [#/hill]//*Ganga sagar | Shoot [#/hill]//*Drilling(Hand sowing) | Shoot [#/hill]//*Transplanting | Plant, population [#/hill]//*Pusa-33 | Plant, population [#/hill]//*Tella-Hamsa | Plant, population [#/hill]//*Nagpur-22 | Plant, population [#/hill]//*Tuljapur-l | Plant, population [#/hill]//*Ganga sagar | Plant, population [#/hill]//*Drilling(Hand sowing) | Plant, population [#/hill]//*Transplanting | Plant, population [#/hill]//*no puddling;Treatment:D0 | Plant, dry matter [g/hill]//*Pusa-33 | Plant, dry matter [g/hill]//*Tella-Hamsa | Plant, dry matter [g/hill]//*Nagpur-22 | Plant, dry matter [g/hill]//*Tuljapur-l | Plant, dry matter [g/hill]//*Ganga sagar | Plant, dry matter [g/hill]//*Drilling(Hand sowing) | Plant, dry matter  [g/hill]//*Transplanting | Panicle [#/hill]//*Pusa-33 | Panicle [#/hill]//*Tella-Hamsa | Panicle [#/hill]//*Nagpur-22 | Panicle [#/hill]//*Tuljapur-l | Panicle [#/hill]//*Ganga sagar | Panicle [#/hill]//*Drilling(Hand sowing) | Panicle [#/hill]//*Transplanting | Panicle, length [cm]//*Pusa-33 | Panicle, length [cm]//*Tella-Hamsa | Panicle, length [cm]//*Nagpur-22 | Panicle, length [cm]//*Tuljapur-l | Panicle, length [cm]//*Ganga sagar | Panicle, length [cm]//*Drilling(Hand sowing) | Panicle, length [cm]//*Transplanting | Branches, rachis [cm]//*Pusa-33 | Branches, rachis [cm]//*Tella-Hamsa | Branches, rachis [cm]//*Nagpur-22 | Branches, rachis [cm]//*Tuljapur-l | Branches, rachis [cm]//*Ganga sagar | Branches, rachis [cm]//*Drilling(Hand sowing) | Branches, rachis [cm]//*Transplanting | Grain [#/hill]//*Pusa-33 | Grain [#/hill]//*Tella-Hamsa | Grain [#/hill]//*Nagpur-22 | Grain [#/hill]//*Tuljapur-l | Grain [#/hill]//*Ganga sagar | Grain [#/hill]//*Drilling(Hand sowing) | Grain [#/hill]//*Transplanting | Panicle, weight [g]//*Pusa-33 | Panicle, weight [g]//*Tella-Hamsa | Panicle, weight [g]//*Nagpur-22 | Panicle, weight [g]//*Tuljapur-l | Panicle, weight [g]//*Ganga sagar | Panicle, weight [g]//*Drilling(Hand sowing) | Panicle, weight [g]//*Transplanting | Sterility [%]//*Pusa-33 | Sterility [%]//*Tella-Hamsa | Sterility [%]//*Nagpur-22 | Sterility [%]//*Tuljapur-l | Sterility [%]//*Ganga sagar | Sterility [%]//*Drilling(Hand sowing) | Sterility [%]//*Transplanting | 1000-grain weight [g]//*Pusa-33 | 1000-grain weight [g]//*Tella-Hamsa | 1000-grain weight [g]//*Nagpur-22 | 1000-grain weight [g]//*Tuljapur-l | 1000-grain weight [g]//*Ganga sagar | 1000-grain weight [g]//*Drilling(Hand sowing) | 1000-grain weight [g]//*Transplanting | Grain yield [q/ha]//*Pusa-33 | Grain yield [q/ha]//*Tella-Hamsa | Grain yield [q/ha]//*Nagpur-22 | Grain yield [q/ha]//*Tuljapur-l | Grain yield [q/ha]//*Ganga sagar | Grain yield [q/ha]//*Drilling(Hand sowing) | Straw yield [q/ha]//*Pusa-33 | Straw yield [q/ha]//*Tella-Hamsa | Straw yield [q/ha]//*Nagpur-22 | Straw yield [q/ha]//*Tuljapur-l | Straw yield [q/ha]//*Ganga sagar | Straw yield [q/ha]//*Drilling(Hand sowing) | Straw yield [q/ha]//*Transplanting | Grain, straw, ratio//*Pusa-33 | Grain, straw, ratio//*Tella-Hamsa | Grain, straw, ratio//*Nagpur-22 | Grain, straw, ratio//*Tuljapur-l | Grain, straw, ratio//*Ganga sagar | Grain, straw, ratio//*Drilling(Hand sowing) | Grain, straw, ratio//*Transplanting | Hulling [%]//*Pusa-33 | Hulling [%]//*Tella-Hamsa | Hulling [%]//*Nagpur-22 | Hulling [%]//*Tuljapur-l | Hulling [%]//*Ganga sagar | Hulling [%]//*Drilling(Hand sowing) | Hulling [%]//*Transplanting | Nitrogen, grain [%]//*Pusa-33 | Nitrogen, grain [%]//*Tella-Hamsa | Nitrogen, grain [%]//*Nagpur-22 | Nitrogen, grain [%]//*Tuljapur-l | Nitrogen, grain [%]//*Ganga sagar | Nitrogen, grain [%]//*Drilling(Hand sowing) | Nitrogen, grain [%]//*Transplanting | Nitrogen, straw  [%]//*Pusa-33 | Nitrogen, straw  [%]//*Tella-Hamsa | Nitrogen, straw  [%]//*Nagpur-22 | Nitrogen, straw  [%]//*Tuljapur-l | Nitrogen, straw  [%]//*Ganga sagar | Nitrogen, straw  [%]//*Drilling(Hand sowing) | Nitrogen, straw  [%]//*Transplanting | Nitrogen, uptake, grain [kg/ha]//*Pusa-33 | Nitrogen, uptake, grain [kg/ha]//*Tella-Hamsa | Nitrogen, uptake, grain [kg/ha]//*Nagpur-22 | Nitrogen, uptake, grain [kg/ha]//*Tuljapur-l | Nitrogen, uptake, grain [kg/ha]//*Ganga sagar | Nitrogen, uptake, grain [kg/ha]//*Drilling(Hand sowing) | Nitrogen, uptake, grain [kg/ha]//*Transplanting | Nitrogen, uptake, straw [kg/ha]//*Pusa-33 | Nitrogen, uptake, straw [kg/ha]//*Tella-Hamsa | Nitrogen, uptake, straw [kg/ha]//*Nagpur-22 | Nitrogen, uptake, straw [kg/ha]//*Tuljapur-l | Nitrogen, uptake, straw  [kg/ha]//*Ganga sagar | Nitrogen, uptake, straw  [kg/ha]//*Drilling(Hand sowing) | Nitrogen, uptake, straw  [kg/ha]//*Transplanting | Nitrogen, uptake,total [kg/ha]//*Pusa-33 | Nitrogen, uptake,total [kg/ha]//*Tella-Hamsa | Nitrogen, uptake,total [kg/ha]//*Nagpur-22 | Nitrogen, uptake,total [kg/ha]//*Tuljapur-l | Nitrogen, uptake,total [kg/ha]//*Ganga sagar | Nitrogen, uptake,total [kg/ha]//*Drilling(Hand sowing) | Nitrogen, uptake,total [kg/ha]//*Transplanting | Phosphorus, grain [%]//*Pusa-33 | Phosphorus, grain  [%]//*Tella-Hamsa | Phosphorus, grain  [%]//*Nagpur-22 | Phosphorus, grain  [%]//*Tuljapur-l | Phosphorus, grain  [%]//*Ganga sagar | Phosphorus, grain  [%]//*Drilling(Hand sowing) | Phosphorus, grain  [%]//*Transplanting | Phosphorus, straw  [%]//*Pusa-33 | Phosphorus, straw  [%]//*Tella-Hamsa | Phosphorus, straw  [%]//*Nagpur-22 | Phosphorus, straw  [%]//*Tuljapur-l | Phosphorus, straw  [%]//*Ganga sagar | Phosphorus, straw  [%]//*Drilling(Hand sowing) | Phosphorus, straw  [%]//*Transplanting | Phosphorus, uptake, grain [kg/ha]//*Pusa-33 | Phosphorus, uptake, grain [kg/ha]//*Tella-Hamsa | Phosphorus, uptake, grain [kg/ha]//*Nagpur-22 | Phosphorus, uptake, grain [kg/ha]//*Tuljapur-l | Phosphorus, uptake, grain [kg/ha]//*Ganga sagar | Phosphorus, uptake, grain [kg/ha]//*Drilling(Hand sowing) | Phosphorus, uptake, grain [kg/ha]//*Transplanting | Phosphorus, uptake, straw [kg/ha]//*Pusa-33 | Phosphorus, uptake, straw [kg/ha]//*Tella-Hamsa | Phosphorus, uptake, straw [kg/ha]//*Nagpur-22 | Phosphorus, uptake, straw [kg/ha]//*Tuljapur-l | Phosphorus, uptake, straw  [kg/ha]//*Ganga sagar | Phosphorus, uptake, straw  [kg/ha]//*Drilling(Hand sowing) | Phosphorus, uptake, straw  [kg/ha]//*Transplanting | Phosphorus, uptake, total [kg/ha]//*Pusa-33 | Phosphorus, uptake, total [kg/ha]//*Tella-Hamsa | Phosphorus, uptake, total [kg/ha]//*Nagpur-22 | Phosphorus, uptake, total [kg/ha]//*Tuljapur-l | Phosphorus, uptake, total [kg/ha]//*Ganga sagar | Phosphorus, uptake, total [kg/ha]//*Drilling(Hand sowing) | Phosphorus, uptake, total [kg/ha]//*Transplanting | Potassium, grain [%]//*Pusa-33 | Potassium, grain  [%]//*Tella-Hamsa | Potassium, grain  [%]//*Nagpur-22 | Potassium, grain  [%]//*Tuljapur-l | Potassium, grain  [%]//*Ganga sagar | Potassium, grain  [%]//*Drilling(Hand sowing) | Potassium, grain  [%]//*Transplanting | Potassium, straw  [%]//*Pusa-33 | Potassium, straw  [%]//*Tella-Hamsa | Potassium, straw  [%]//*Nagpur-22 | Potassium, straw  [%]//*Tuljapur-l | Potassium, straw  [%]//*Ganga sagar | Potassium, straw  [%]//*Drilling(Hand sowing) | Potassium, straw  [%]//*Transplanting | Potassium, uptake, grain [kg/ha]//*Pusa-33 | Potassium, uptake, grain [kg/ha]//*Tella-Hamsa | Potassium, uptake, grain [kg/ha]//*Nagpur-22 | Potassium, uptake, grain [kg/ha]//*Tuljapur-l | Potassium, uptake, grain [kg/ha]//*Ganga sagar | Potassium, uptake, grain [kg/ha]//*Drilling(Hand sowing) | Potassium, uptake,grain [kg/ha]//*Transplanting | Potassium, uptake, straw [kg/ha]//*Pusa-33 | Potassium, uptake, straw [kg/ha]//*Tella-Hamsa | Potassium, uptake, straw [kg/ha]//*Nagpur-22 | Potassium, uptake, straw [kg/ha]//*Tuljapur-l | Potassium, uptake, straw  [kg/ha]//*Ganga sagar | Potassium, uptake, straw  [kg/ha]//*Drilling(Hand sowing) | Potassium, uptake, straw  [kg/ha]//*Transplanting | Potassium, uptake, total [kg/ha]//*Pusa-33 | Potassium, uptake, total [kg/ha]//*Tella-Hamsa | Potassium, uptake, total [kg/ha]//*Nagpur-22 | Potassium, uptake, total [kg/ha]//*Tuljapur-l | Potassium, uptake, total [kg/ha]//*Ganga sagar | Potassium, uptake, total [kg/ha]//*Drilling(Hand sowing) | Potassium, uptake, total [kg/ha]//*Transplanting

Structure 2:

In [13]:
import pandas as pd
from pathlib import Path

# 1. Sheet-wise DataFrames store karne ke liye dictionary
master_sheets = {
    "Timeseries": [],
    "Weather data": [],
    "Treatments": [],
    "Timeline field activities": []
}

# 2. Sabhi 93 files par loop chalana aur metadata append karna
for file_path in historical_files:
    try:
        excel = pd.ExcelFile(file_path)
        file_name = file_path.name
        region = file_path.parent.name  # Central_India_Region ya Gangetic_Plain_Region
        
        for sheet in excel.sheet_names:
            if sheet in master_sheets:
                df = pd.read_excel(file_path, sheet_name=sheet)
                
                # Source tracking ke liye metadata columns add kar rahe hain
                df.insert(0, "Source_File", file_name)
                df.insert(1, "Region", region)
                
                master_sheets[sheet].append(df)
    except Exception as e:
        print(f"Error reading {file_path.name}: {e}")

# 3. Har sheet type ko ek single Master DataFrame mein merge karna
combined_datasets = {}
print("--- Consolidation Summary ---")
for sheet_name, df_list in master_sheets.items():
    if df_list:
        # Concatenate keeping all columns (union of columns across files)
        combined_df = pd.concat(df_list, ignore_index=True)
        combined_datasets[sheet_name] = combined_df
        print(f"Sheet: '{sheet_name}' -> Total Rows: {combined_df.shape[0]}, Total Columns: {combined_df.shape[1]}")

# 4. Cleaned/Merged data ko CSVs mein save karna
processed_dir = PROJECT_ROOT / "data" / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

for sheet_name, df in combined_datasets.items():
    clean_name = sheet_name.lower().replace(" ", "_")
    output_path = processed_dir / f"historical_{clean_name}.csv"
    df.to_csv(output_path, index=False)
    print(f"Saved: {output_path.name}")

C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, "Source_File", file_name)
C:\Users\adnan\AppData\Local\Temp\ipykernel_14104\849480230.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1, "Region", region)

--- Consolidation Summary ---
Sheet: 'Timeseries' -> Total Rows: 877, Total Columns: 5202
Sheet: 'Weather data' -> Total Rows: 1539, Total Columns: 53
Sheet: 'Treatments' -> Total Rows: 876, Total Columns: 5
Sheet: 'Timeline field activities' -> Total Rows: 1210, Total Columns: 19
Saved: historical_timeseries.csv
Saved: historical_weather_data.csv
Saved: historical_treatments.csv
Saved: historical_timeline_field_activities.csv

In [14]:
for sheet_name, df in combined_datasets.items():

    print("\n" + "=" * 80)
    print(f"DATASET: {sheet_name}")
    print("=" * 80)

    print("Shape:", df.shape)

    print("\nMissing values:")
    print("Total missing:", df.isna().sum().sum())

    print("\nDuplicate rows:")
    print(df.duplicated().sum())

    print("\nData types:")
    print(df.dtypes.value_counts())

    print("\nFirst 5 columns:")
    print(df.columns[:5].tolist())

    print("\nLast 5 columns:")
    print(df.columns[-5:].tolist())

================================================================================
DATASET: Timeseries
================================================================================
Shape: (877, 5202)

Missing values:
Total missing: 4515433

Duplicate rows:
17

Data types:
float64    5168
str          21
object       13
Name: count, dtype: int64

First 5 columns:
['Source_File', 'Region', 'Event', 'Serial number []', 'Country []']

Last 5 columns:
['Potassium, plant-available [kg/ha]//*Treatment:G2', 'Potassium, plant-available [kg/ha]//*Treatment:G3', 'Potassium, plant-available [kg/ha]//*Treatment:G4', 'Potassium, plant-available [kg/ha]//*Treatment:G5', 'Potassium, plant-available [kg/ha]//*Treatment:G6']

================================================================================
DATASET: Weather data
================================================================================
Shape: (1539, 53)

Missing values:
Total missing: 62379

Duplicate rows:
0

Data types:
float64    45
str         6
object      2
Name: count, dtype: int64

First 5 columns:
['Source_File', 'Region', 'Location []', 'Lat [ºN]', 'Lon [ºE]']

Last 5 columns:
['Lon [°E]', 'Relative humidity, mimimum [%]', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

================================================================================
DATASET: Treatments
================================================================================
Shape: (876, 5)

Missing values:
Total missing: 887

Duplicate rows:
0

Data types:
str       4
object    1
Name: count, dtype: int64

First 5 columns:
['Source_File', 'Region', 'Treatments', 'Symbol', 'Remark']

Last 5 columns:
['Source_File', 'Region', 'Treatments', 'Symbol', 'Remark']

================================================================================
DATASET: Timeline field activities
================================================================================
Shape: (1210, 19)

Missing values:
Total missing: 15552

Duplicate rows:
49

Data types:
str        10
object      7
float64     2
Name: count, dtype: int64

First 5 columns:
['Source_File', 'Region', 'Sl.No', 'Agricultural operation', 'Crop']

Last 5 columns:
['Date of operation-D2', 'Date of operation-D3', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']

In [15]:
for sheet_name, df in combined_datasets.items():

    print("\n" + "=" * 70)
    print(f"DATASET: {sheet_name}")
    print("=" * 70)

    print("Shape:", df.shape)
    print("Total missing:", df.isna().sum().sum())
    print("Duplicate rows:", df.duplicated().sum())
    print("Data types:")
    print(df.dtypes.value_counts())

======================================================================
DATASET: Timeseries
======================================================================
Shape: (877, 5202)
Total missing: 4515433
Duplicate rows: 17
Data types:
float64    5168
str          21
object       13
Name: count, dtype: int64

======================================================================
DATASET: Weather data
======================================================================
Shape: (1539, 53)
Total missing: 62379
Duplicate rows: 0
Data types:
float64    45
str         6
object      2
Name: count, dtype: int64

======================================================================
DATASET: Treatments
======================================================================
Shape: (876, 5)
Total missing: 887
Duplicate rows: 0
Data types:
str       4
object    1
Name: count, dtype: int64

======================================================================
DATASET: Timeline field activities
======================================================================
Shape: (1210, 19)
Total missing: 15552
Duplicate rows: 49
Data types:
str        10
object      7
float64     2
Name: count, dtype: int64

In [16]:
for sheet_name, df in combined_datasets.items():

    empty_cols = df.columns[df.isna().all()].tolist()

    print("\n" + "=" * 70)
    print(f"DATASET: {sheet_name}")
    print("=" * 70)

    print("Total columns:", df.shape[1])
    print("Completely empty columns:", len(empty_cols))

    if len(empty_cols) > 0:
        print("First 20 empty columns:")
        print(empty_cols[:20])

======================================================================
DATASET: Timeseries
======================================================================
Total columns: 5202
Completely empty columns: 34
First 20 empty columns:
['Plant, population [#/hill]//*Tella-Hamsa.1', 'Plant, population [#/hill]//*Nagpur-22.1', 'Grain [#/panicle]//*Tella-Hamsa', 'Grain [#/panicle]//*Nagpur-22', 'Nitrogen, uptake, total [kg/ha]//*Tella-Hamsa', 'Nitrogen, uptake, total [kg/ha]//*Nagpur-22', 'Nitrogen, uptake, total [kg/ha]//*Ganga sagar', 'Nitrogen, uptake, total [kg/ha]//*Drilling(Hand sowing)', 'Nitrogen, uptake, total [kg/ha]//*Transplanting', 'Potassium, uptake, grain [kg/ha]//*Transplanting', 'shoot [#/hill]//*Pusa-33.1', 'shoot [#/hill]//*Tella-Hamsa', 'shoot [#/hill]//*Nagpur-22', 'shoot [#/hill]//*Ganga sagar', 'shoot [#/hill]//*Drilling(Hand sowing)', 'shoot [#/hill]//*Transplanting', 'Plant, dry matter [g/hill]//*Transplanting', 'Grain [#/ panicle]//*Tella-Hamsa', 'Grain [#/ panicle]//*Nagpur-22', 'Grain [#/ panicle]//*Ganga sagar']

======================================================================
DATASET: Weather data
======================================================================
Total columns: 53
Completely empty columns: 2
First 20 empty columns:
['Unnamed: 10', 'Unnamed: 11']

======================================================================
DATASET: Treatments
======================================================================
Total columns: 5
Completely empty columns: 0

======================================================================
DATASET: Timeline field activities
======================================================================
Total columns: 19
Completely empty columns: 1
First 20 empty columns:
['Unnamed: 3']

In [17]:
for sheet_name, df in combined_datasets.items():
    before = df.shape[1]

    combined_datasets[sheet_name] = df.dropna(axis=1, how="all")

    after = combined_datasets[sheet_name].shape[1]

    print(
        f"{sheet_name}: "
        f"{before} → {after} columns "
        f"({before - after} empty columns removed)"
    )

Timeseries: 5202 → 5168 columns (34 empty columns removed)
Weather data: 53 → 51 columns (2 empty columns removed)
Treatments: 5 → 5 columns (0 empty columns removed)
Timeline field activities: 19 → 18 columns (1 empty columns removed)

In [18]:
for sheet_name, df in combined_datasets.items():

    clean_name = sheet_name.lower().replace(" ", "_")
    output_path = processed_dir / f"historical_{clean_name}.csv"

    df.to_csv(output_path, index=False)

    print(f"Saved: {output_path.name} | Shape: {df.shape}")

Saved: historical_timeseries.csv | Shape: (877, 5168)
Saved: historical_weather_data.csv | Shape: (1539, 51)
Saved: historical_treatments.csv | Shape: (876, 5)
Saved: historical_timeline_field_activities.csv | Shape: (1210, 18)

In [19]:
for sheet_name, df in combined_datasets.items():
    duplicate_count = df.duplicated().sum()

    print(f"{sheet_name}: {duplicate_count} duplicate rows")

Timeseries: 17 duplicate rows
Weather data: 0 duplicate rows
Treatments: 0 duplicate rows
Timeline field activities: 49 duplicate rows

In [20]:
# Inspect duplicate rows in Timeseries
timeseries_duplicates = combined_datasets["Timeseries"][
    combined_datasets["Timeseries"].duplicated(keep=False)
]

print("Timeseries duplicate rows:", timeseries_duplicates.shape)
display(timeseries_duplicates)

Timeseries duplicate rows: (34, 5168)

,Source_File,Region,Event,Serial number [],Country [],Journal/report title [],Author(s) [],Uniform resource locator/link to reference [],Journal/report publisher [],Year [],...,"Phosphorus, plant-available [kg/ha]//*Treatment:G6","Potassium, plant-available [kg/ha]//*Treatment:F1","Potassium, plant-available [kg/ha]//*Treatment:F2","Potassium, plant-available [kg/ha]//*Treatment:F3","Potassium, plant-available [kg/ha]//*Treatment:G1","Potassium, plant-available [kg/ha]//*Treatment:G2","Potassium, plant-available [kg/ha]//*Treatment:G3","Potassium, plant-available [kg/ha]//*Treatment:G4","Potassium, plant-available [kg/ha]//*Treatment:G5","Potassium, plant-available [kg/ha]//*Treatment:G6"
95,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,0 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,30 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,60 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,90 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,0 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,30 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,60 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,90 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,0 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,30 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,60 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,90 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,0 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,30 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,60 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,IND_RI_JAB_2001.xlsx,Central_India_Region,IND_RI_JAB_2001,90 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,0 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,30 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,60 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,90 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,0 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,30 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,60 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,90 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,0 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,30 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,60 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,90 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,0 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,30 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,60 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,IND_RI_JAB_2002.xlsx,Central_India_Region,IND_RI_JAB_2002,90 DAS/DAT,India,Development of Agro-Techniques for Sustainable...,NaN,https://krishikosh.egranth.ac.in/assets/pdfjs/...,"Jawaharlal Nehru Krishi Vishwa Vidyalaya, Jaba...",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,IND_RI_KAU_1986.xlsx,Gangetic_Plain_Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,IND_RI_KAU_1986.xlsx,Gangetic_Plain_Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Inspect duplicate rows in Timeline field activities
timeline_duplicates = combined_datasets["Timeline field activities"][
    combined_datasets["Timeline field activities"].duplicated(keep=False)
]

print("Timeline duplicate rows:", timeline_duplicates.shape)
display(timeline_duplicates)

Timeline duplicate rows: (63, 18)

,Source_File,Region,Sl.No,Agricultural operation,Crop,Rice establishment methods,Date of operation,Date of operation,CROP,Remarks,SI.No.,Seed rate,Date of operation-D1,Date of operation-D2,Date of operation-D3,Unnamed: 5,Unnamed: 6,Unnamed: 7
368,IND_RI_JAB_2014.xlsx,Central_India_Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,IND_RI_JAB_2014.xlsx,Central_India_Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
370,IND_RI_JAB_2014.xlsx,Central_India_Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
371,IND_RI_JAB_2014.xlsx,Central_India_Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
372,IND_RI_JAB_2014.xlsx,Central_India_Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,IND_RI_VAD_2017.xlsx,Central_India_Region,4,Fourth transplanting,NaN,NaN,2017-10-12 00:00:00,NaN,Rice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
675,IND_RI_VAD_2017.xlsx,Central_India_Region,1,First transplanting,NaN,NaN,2017-08-29 00:00:00,NaN,Rice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
676,IND_RI_VAD_2017.xlsx,Central_India_Region,2,Second transplanting,NaN,NaN,2017-09-13 00:00:00,NaN,Rice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
677,IND_RI_VAD_2017.xlsx,Central_India_Region,3,Third transplanting,NaN,NaN,2017-09-27 00:00:00,NaN,Rice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,IND_RI_VAD_2017.xlsx,Central_India_Region,4,Fourth transplanting,NaN,NaN,2017-10-12 00:00:00,NaN,Rice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
display(
    timeline_duplicates[
        ["Source_File", "Region"]
    ]
)

              Source_File                Region
368  IND_RI_JAB_2014.xlsx  Central_India_Region
369  IND_RI_JAB_2014.xlsx  Central_India_Region
370  IND_RI_JAB_2014.xlsx  Central_India_Region
371  IND_RI_JAB_2014.xlsx  Central_India_Region
372  IND_RI_JAB_2014.xlsx  Central_India_Region
..                    ...                   ...
673  IND_RI_VAD_2017.xlsx  Central_India_Region
675  IND_RI_VAD_2017.xlsx  Central_India_Region
676  IND_RI_VAD_2017.xlsx  Central_India_Region
677  IND_RI_VAD_2017.xlsx  Central_India_Region
678  IND_RI_VAD_2017.xlsx  Central_India_Region

[63 rows x 2 columns]

In [23]:
print(timeline_duplicates.columns.tolist())

['Source_File', 'Region', 'Sl.No', 'Agricultural operation', 'Crop', 'Rice establishment methods', 'Date of operation', 'Date of operation ', 'CROP', 'Remarks', 'SI.No.', 'Seed rate', 'Date of operation-D1', 'Date of operation-D2', 'Date of operation-D3', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']

In [24]:
display(
    timeline_duplicates[
        [
            "Source_File",
            "Region",
            "Agricultural operation",
            "Crop",
            "CROP",
            "Date of operation",
            "Date of operation ",
            "Remarks"
        ]
    ]
)

,Source_File,Region,Agricultural operation,Crop,CROP,Date of operation,Date of operation,Remarks
368,IND_RI_JAB_2014.xlsx,Central_India_Region,NaN,NaN,NaN,NaN,NaN,NaN
369,IND_RI_JAB_2014.xlsx,Central_India_Region,NaN,NaN,NaN,NaN,NaN,NaN
370,IND_RI_JAB_2014.xlsx,Central_India_Region,NaN,NaN,NaN,NaN,NaN,NaN
371,IND_RI_JAB_2014.xlsx,Central_India_Region,NaN,NaN,NaN,NaN,NaN,NaN
372,IND_RI_JAB_2014.xlsx,Central_India_Region,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
673,IND_RI_VAD_2017.xlsx,Central_India_Region,Fourth transplanting,NaN,Rice,2017-10-12 00:00:00,NaN,NaN
675,IND_RI_VAD_2017.xlsx,Central_India_Region,First transplanting,NaN,Rice,2017-08-29 00:00:00,NaN,NaN
676,IND_RI_VAD_2017.xlsx,Central_India_Region,Second transplanting,NaN,Rice,2017-09-13 00:00:00,NaN,NaN
677,IND_RI_VAD_2017.xlsx,Central_India_Region,Third transplanting,NaN,Rice,2017-09-27 00:00:00,NaN,NaN
678,IND_RI_VAD_2017.xlsx,Central_India_Region,Fourth transplanting,NaN,Rice,2017-10-12 00:00:00,NaN,NaN

In [25]:
timeline_df = combined_datasets["Timeline field activities"]

before = len(timeline_df)

timeline_df = timeline_df.dropna(
    axis=0,
    how="all"
)

after = len(timeline_df)

combined_datasets["Timeline field activities"] = timeline_df

print(f"Rows: {before} → {after}")
print(f"Removed: {before - after}")

Rows: 1210 → 1210
Removed: 0

In [26]:
print(
    "Timeline duplicates:",
    combined_datasets["Timeline field activities"].duplicated().sum()
)

Timeline duplicates: 49

In [27]:
row = combined_datasets["Timeline field activities"].iloc[368]

display(row[row.notna()])

Source_File    IND_RI_JAB_2014.xlsx
Region         Central_India_Region
Name: 368, dtype: object

In [28]:
timeline_df = combined_datasets["Timeline field activities"]

before = len(timeline_df)

timeline_df = timeline_df.dropna(
    subset=[
        "Agricultural operation",
        "Crop",
        "CROP",
        "Date of operation",
        "Date of operation "
    ],
    how="all"
)

combined_datasets["Timeline field activities"] = timeline_df

after = len(timeline_df)

print(f"Rows: {before} → {after}")
print(f"Removed: {before - after}")

Rows: 1210 → 1173
Removed: 37

In [29]:
for sheet_name, df in combined_datasets.items():
    clean_name = sheet_name.lower().replace(" ", "_")
    output_path = processed_dir / f"historical_{clean_name}.csv"

    df.to_csv(output_path, index=False)

    print(f"Saved: {output_path.name} | Shape: {df.shape}")

Saved: historical_timeseries.csv | Shape: (877, 5168)
Saved: historical_weather_data.csv | Shape: (1539, 51)
Saved: historical_treatments.csv | Shape: (876, 5)
Saved: historical_timeline_field_activities.csv | Shape: (1173, 18)

In [30]:
from collections import Counter

uav_files = [p for p in UAV_DIR.rglob("*") if p.is_file()]

print("Total files:", len(uav_files))

extensions = Counter(
    p.suffix.lower() if p.suffix else "[no extension]"
    for p in uav_files
)

print("\nFile types:")
for ext, count in extensions.most_common():
    print(ext, ":", count)

Total files: 253810

File types:
.xml : 99504
.tfw : 49752
.tiff : 49752
.ovr : 49752
[no extension] : 5037
.txt : 4
.csv : 4
.xlsx : 2
.ds_store : 2
.md : 1

In [31]:
readme_files = list(UAV_DIR.glob("README*"))

for file in readme_files:
    print(f"\n--- {file.name} ---\n")
    print(file.read_text(errors="ignore"))

--- README.md ---

# Multitemporal multispectral imagery for rice yield and phenology prediction

[https://doi.org/10.5061/dryad.v41ns1s4z](https://doi.org/10.5061/dryad.v41ns1s4z)

The dataset includes five experimentsÂ conducted at the USDA-ARS Dale Bumpers National Rice Research Center in Stuttgart, AR in 2021 and 2022: two nitrogen rate studies, a private hybrid study, an inbred study, and a genetic diversity study. A randomized block design was established in both years, with 252 total plots in 2021 and 180 plots in 2022. Plots were imaged at 12 timepoints throughout the season in both years.

## Description of the data and file structure

The dataset includes images for each plot as well as extracted features (49 features including vegetation indices, texture properties, and thermal features), and per-plot yield and phenology data. Images are named by plot within separate directories for each flyover date. Test and train sets are based on a 'leave-one-replicate-out' approach, where one replicate plot for each experimental treatment was randomly assigned to the test set.

Additionally, the dataset includes weather data at the site for 2021 and 2022 (`RREC_DAILY_2021.xlsx` and `RREC_DAILY_2022.xlsx`).

### File structure

```
Agronomic
|- 2021/
|  |- constant_agronomic_traits_2021.csv
|- 2022/
|  |- constant_agronomic_traits_2022.csv

Images
|- Train/
|  |- Flyover-date/
|  |  |- Plot-number/
|  |  |  |- blue [.tfw, .tiff, .tiff.ovr, .tiff.aux.xml, .tiff.xml]
|  |  |  |- green [.tfw, .tiff, .tiff.ovr, .tiff.aux.xml, .tiff.xml]
|  |  |  |- red [.tfw, .tiff, .tiff.ovr, .tiff.aux.xml, .tiff.xml]
|  |  |  |- red_edge [.tfw, .tiff, .tiff.ovr, .tiff.aux.xml, .tiff.xml]
|  |  |  |- nir [.tfw, .tiff, .tiff.ovr, .tiff.aux.xml, .tiff.xml]
|- Test/
|  |- Flyover-date/
|  |  |- Plot-number/
|  |  |  |- blue [.tfw, .tiff, .tiff.ovr, .tiff.aux.xml, .tiff.xml]
|  |  |  |- green [.tfw, .tiff, .tiff.ovr, .tiff.aux.xml, .tiff.xml]
|  |  |  |- red [.tfw, .tiff, .tiff.ovr, .tiff.aux.xml, .tiff.xml]
|  |  |  |- red_edge [.tfw, .tiff, .tiff.ovr, .tiff.aux.xml, .tiff.xml]
|  |  |  |- nir [.tfw, .tiff, .tiff.ovr, .tiff.aux.xml, .tiff.xml]

```

### Agronomic and trait data

#### Column headers:

Seeding_Rate: seeding rate in kilograms/hectare
Nitrogen_Rate: fertilizer rate in lbs/acre
Yield: yield in metric tons/hectare
Emergence_Date_DOY: emergence date, Julian day
Heading_25: days from emergence to 25% heading
Heading_50: days from emergence to 50% heading
Heading_100: days from emergence to 100% heading
Final_Lodge: % lodging final

### Weather data

#### Tabs:

`UAV growing season`Â is a subset of daily precipitation and temperature values from `RREC DAILY 2021`Â or `RREC DAILY 2022`Â during the growing season.

#### Abbreviations:

PAR: photosynthetically active radiation
Deg: degree
RH: relative humidity

## Code/Software

Code to reproduce the analyses is available at [https://github.com/FareedFarag/TPPJ-Modeling-Code](https://github.com/FareedFarag/TPPJ-Modeling-Code).

A Geographic Information System (GIS) such as [QGIS](https://www.qgis.org) is required to open the image files.

In [32]:
for file in UAV_DIR.glob("*.xlsx"):
    print("\n==============================")
    print(file.name)
    print("==============================")

    excel = pd.ExcelFile(file)
    print("Sheets:", excel.sheet_names)

    for sheet in excel.sheet_names:
        df = pd.read_excel(file, sheet_name=sheet)
        print(f"{sheet}: {df.shape}")
        print(df.columns.tolist())

==============================
RREC_DAILY_2021.xlsx
==============================
Sheets: ['UAV growing season', 'RREC_DAILY_2021']
UAV growing season: (132, 12)
['TIMESTAMP', 'Rain_Tot', 'Air_Temp_Min', 'Air_Temp_Max', 'Air_Temp_Avg', 'Soil_Temp_2_in_Min', 'Soil_Temp_2_in_Max', 'Soil_Temp_2_in_Avg', 'Soil_Temp_5_in_Min', 'Soil_Temp_5_in_Max', 'Soil_Temp_5_in_Avg', 'RECORD']
RREC_DAILY_2021: (367, 25)
['TIMESTAMP', 'RECORD', 'Rain_Tot', 'Air_Temp_Min', 'Air_Temp_Max', 'Air_Temp_Avg', 'RH_Min', 'RH_Max', 'Wind_Speed_Min', 'Wind_Speed_Max', 'Wind_Speed_Avg', 'Wind_Direction', 'Wind_Direction_SD', 'Solar_Flux_Density_Max', 'Solar_Flux_Density_Avg', 'Solar_Total_Flux_Tot', 'PAR_Flux_Density_Max', 'PAR_Flux_Density_Avg', 'PAR_Total_Flux_Tot', 'Soil_Temp_2_in_Min', 'Soil_Temp_2_in_Max', 'Soil_Temp_2_in_Avg', 'Soil_Temp_5_in_Min', 'Soil_Temp_5_in_Max', 'Soil_Temp_5_in_Avg']

==============================
RREC_DAILY_2022.xlsx
==============================
Sheets: ['UAV growing season', 'RREC_DAILY_2022']
UAV growing season: (138, 12)
['TIMESTAMP', 'Rain_Tot', 'Air_Temp_Min', 'Air_Temp_Max', 'Air_Temp_Avg', 'Soil_Temp_2_in_Min', 'Soil_Temp_2_in_Max', 'Soil_Temp_2_in_Avg', 'Soil_Temp_5_in_Min', 'Soil_Temp_5_in_Max', 'Soil_Temp_5_in_Avg', 'RECORD']
RREC_DAILY_2022: (367, 25)
['TIMESTAMP', 'RECORD', 'Rain_Tot', 'Air_Temp_Min', 'Air_Temp_Max', 'Air_Temp_Avg', 'RH_Min', 'RH_Max', 'Wind_Speed_Min', 'Wind_Speed_Max', 'Wind_Speed_Avg', 'Wind_Direction', 'Wind_Direction_SD', 'Solar_Flux_Density_Max', 'Solar_Flux_Density_Avg', 'Solar_Total_Flux_Tot', 'PAR_Flux_Density_Max', 'PAR_Flux_Density_Avg', 'PAR_Total_Flux_Tot', 'Soil_Temp_2_in_Min', 'Soil_Temp_2_in_Max', 'Soil_Temp_2_in_Avg', 'Soil_Temp_5_in_Min', 'Soil_Temp_5_in_Max', 'Soil_Temp_5_in_Avg']

In [33]:
uav_weather = []

for year in [2021, 2022]:

    file_path = UAV_DIR / f"RREC_DAILY_{year}.xlsx"

    df = pd.read_excel(
        file_path,
        sheet_name=f"RREC_DAILY_{year}"
    )

    df["Year"] = year

    uav_weather.append(df)

uav_weather_df = pd.concat(
    uav_weather,
    ignore_index=True
)

print("Shape:", uav_weather_df.shape)
display(uav_weather_df.head())

Shape: (734, 26)

,TIMESTAMP,RECORD,Rain_Tot,Air_Temp_Min,Air_Temp_Max,Air_Temp_Avg,RH_Min,RH_Max,Wind_Speed_Min,Wind_Speed_Max,...,PAR_Flux_Density_Max,PAR_Flux_Density_Avg,PAR_Total_Flux_Tot,Soil_Temp_2_in_Min,Soil_Temp_2_in_Max,Soil_Temp_2_in_Avg,Soil_Temp_5_in_Min,Soil_Temp_5_in_Max,Soil_Temp_5_in_Avg,Year
0,TS,RN,inch,Deg F,Deg F,Deg F,%,%,miles/hour,miles/hour,...,umol/s/m^2,umol/s/m^2,mmol/m^2,Deg F,Deg F,Deg F,Deg F,Deg F,Deg F,2021
1,NaN,NaN,Tot,Min,Max,Avg,Min,Max,Min,Max,...,Max,Avg,Tot,Min,Max,Avg,Min,Max,Avg,2021
2,2021-01-01 00:00:00,21,1.6,34.67,40.98,36.99,98.3,100,4.424,19,...,284.8,39.23,3389.679,44.56,48.98,46.12,46.4,50.56,48.05,2021
3,2021-01-02 00:00:00,22,0.31,40.49,46.5,42.59,77.08,100,0,25.69,...,1182,71.51,6178.217,44.83,46.45,45.83,46.4,47.24,46.94,2021
4,2021-01-03 00:00:00,23,0.11,34.73,41.89,39.69,81.6,97.4,0,17.9,...,714.7,72.7,6280.975,43.32,46.58,45.35,45.94,47.21,46.72,2021

In [34]:
output_path = PROJECT_ROOT / "data" / "processed" / "uav_weather_daily.csv"

uav_weather_df.to_csv(
    output_path,
    index=False
)

print("Saved:", output_path)

Saved: C:\Users\adnan\PaddyVision-AI\data\processed\uav_weather_daily.csv

In [35]:
icar_file = next(ICAR_DIR.glob("*.csv"))

df_icar = pd.read_csv(
    icar_file,
    skiprows=1
)

df_icar.columns = [
    "Year",
    "Area_Ha",
    "Production_Tonnes",
    "Yield_Kg_Ha"
]

icar_processed_path = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "icar_rice_clean.csv"
)

df_icar.to_csv(
    icar_processed_path,
    index=False
)

print("Saved:", icar_processed_path)
print("Shape:", df_icar.shape)
display(df_icar.head())

Saved: C:\Users\adnan\PaddyVision-AI\data\processed\icar_rice_clean.csv
Shape: (27, 4)

   Year      Area_Ha  Production_Tonnes  Yield_Kg_Ha
0  2023  47828289.10        137824576.0       2882.0
1  2022  47831997.65        135755160.3       2838.0
2  2021  46278675.43        129471418.2       2798.0
3  2020  45768687.00        124368315.9       2717.0
4  2019  43662297.10        118870319.3       2722.0

In [36]:
# WeedyRice dataset inspection

print("WeedyRice folder:", WEEDY_DIR)

items = list(WEEDY_DIR.iterdir())

print("Total top-level items:", len(items))

for item in items[:50]:
    print(item.name, "->", "Folder" if item.is_dir() else "File")

WeedyRice folder: C:\Users\adnan\PaddyVision-AI\data\raw\weedy-rice
Total top-level items: 9
Masks -> Folder
Metadata -> Folder
Multispectral -> Folder
Overlay -> Folder
readme.md -> File
RGB -> Folder
test_list.txt -> File
train_list.txt -> File
val_list.txt -> File

In [37]:
from collections import Counter

file_extensions = Counter()

for file_path in WEEDY_DIR.rglob("*"):
    if file_path.is_file():
        ext = file_path.suffix.lower()
        file_extensions[ext if ext else "[no extension]"] += 1

print("File type counts:")
for ext, count in file_extensions.most_common():
    print(f"{ext}: {count}")

File type counts:
.tif: 2936
.jpg: 1468
.png: 734
.txt: 4
.csv: 2
.md: 1

In [38]:
readme_files = list(WEEDY_DIR.rglob("*.md"))

for file in readme_files:
    print(file)

C:\Users\adnan\PaddyVision-AI\data\raw\weedy-rice\readme.md

In [39]:
readme_path = readme_files[0]

with open(readme_path, "r", encoding="utf-8") as f:
    readme_text = f.read()

print(readme_text)

# WeedyRice-RGBMS-DB: UAV Imagery Dataset for Semantic Segmentation

# Introduction

WeedyRice-RGBMS-DB is a curated dataset of UAV-acquired imagery for the semantic segmentation. The imagery was captured using the DJI Mavic 3 Multispectral (M3M) platform. All RGB images, multispectral bands, and segmentation masks are spatially aligned, allowing pixel-level correspondence across modalities. Metadata is included to support tasks in image analysis, geospatial processing, segmentation, and machine learning.

# 📁 Directory Structure

WeedyRice-RGBMS-DB/
│
├── RGB/                        # RGB images from UAV (JPEG format)
│   ├── DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m.JPG
│   ├── DJI_DateTime_2024_06_02_13_42_0036_lat_10.3040274_lon_105.2619303_alt_19.998m.JPG
│   └── ...
│
├── Multispectral/              # Multispectral images by band (TIFF format)
│   ├── DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m_G.TIF     # Green
│   ├── DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m_NIR.TIF   # Near Infrared
│   ├── DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m_R.TIF     # Red
│   ├── DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m_RE.TIF    # Red Edge
│   └── ...
│
├── Masks/                      # Ground-truth masks cho segmentation (PNG format)
│   ├── DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m.png
│   ├── DJI_DateTime_2024_06_02_13_42_0036_lat_10.3040274_lon_105.2619303_alt_19.998m.png
│   └── ...
│
├── Metadata/                   # Information about images, coordinates, timestamps, and camera settings...
│   ├── filename_mapping.csv    # Original_filename and standardized_filename
│   ├── image_metadata.csv      # Original_filename,acquisition_date, temporal, spatial, and sensor information
│   └── readme.txt              # Description of metadata fields
│
├── Overlay/                    # Overlay images with polygon annotations (JPEG format)
│   ├── DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m.JPG
│   ├── DJI_DateTime_2024_06_02_13_42_0036_lat_10.3040274_lon_105.2619303_alt_19.998m.JPG
│   └── ...


└── README.md                   # Detailed description and instructions for using the dataset

#Data Acquisition

	- Platform: DJI Mavic 3 Multispectral (M3M)
	- RGB Sensor: FC6520 (JPEG, 5280×3956)
	- Multispectral Sensor: MSX01 (TIFF, 2592×1944)
	- Spectral Bands: Green, Red, Red Edge, Near-Infrared (NIR)
	- Flight Altitude: ~12m and 20m above ground level (AGL)
	- Coordinate System: WGS 84 / UTM zone 48N
	- Acquisition Period: June 2024 – January 2025
	- Location: An Giang Province, Mekong Delta, Vietnam

# 🗂️ Metadata Details

## filename_mapping.csv

- original_filename: The original file name assigned by the UAV
- standardized_filename: File name including acquisition time, GPS, and altitude for consistency

## image_metadata.csv

Each row contains metadata for one image (RGB or MS), including:
- original_filename: UAV image name
- acquisition_date: Date of capture (YYYY-MM-DD)
- time: Time of capture (HH:MM:SS)
- latitude, longitude: GPS location of image center
- altitude: Altitude in meters with "m" suffix
- camera_model: FC6520 for RGB, MSX01 for multispectral
- sensor_type: Either RGB or MS
- band: One of Green, Red, Red Edge, NIR (empty for RGB)

# Use Cases

## Weedy rice detection and segmentation

The purpose of this dataset is to support the development of deep learning models for detecting weedy rice and performing pixel-by-pixel segmentation in cultivated rice fields. Using aligned ground-truth masks and high-resolution RGB images, researchers can train supervised models such as traditional U-Net or U-Net with modern encoder like SegFormer to localize and quantify weed presence. The provided spatial metadata enables spatially-aware training or integration with field maps. This use case contributes to automated weed monitoring, early intervention, and yield preservation in rice production systems.

## Multispectral data fusion

Each RGB image is accompanied by four corresponding spectral bands: Green, Red, Red Edge, and Near-Infrared (NIR), captured simultaneously using the DJI M3M platform. These spectral bands are spatially aligned with the RGB images, enabling pixel-level correspondence.

This alignment allows the use of advanced data fusion strategies such as:

- Early fusion: Channel stacking of RGB + Spectral bands (e.g., 7-channel input)
- Late fusion: Feature-level fusion of parallel encoders
- Index-based fusion: Integration of vegetation indices (e.g., NDVI, NDRE) as auxiliary inputs

Researchers can explore these approaches to improve weed detection performance and enhance early|late-stage classification in precision agriculture applications.

# Usage Instructions

1. Use filename_mapping.csv to convert raw UAV filenames to standardized names.
2. Use image_metadata.csv to filter and query image data by sensor type, date, GPS, and spectral band.
3. All RGB, multispectral images, and segmentation masks are spatially aligned. This allows direct use in semantic segmentation and multimodal data fusion pipelines without additional registration.

This dataset accompanies the article submitted to Data in Brief titled "A Dataset of Aligned RGB and Multispectral UAV Imagery for Semantic Segmentation of Weedy Rice".

In [40]:
# Show sample files from WeedyRice dataset

all_files = [
    p for p in WEEDY_DIR.rglob("*")
    if p.is_file()
]

for file_path in all_files[:30]:
    print(file_path.relative_to(WEEDY_DIR))

readme.md
test_list.txt
train_list.txt
val_list.txt
Masks\DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m.png
Masks\DJI_DateTime_2024_06_02_13_42_0036_lat_10.3040274_lon_105.2619303_alt_19.998m.png
Masks\DJI_DateTime_2024_06_02_13_43_0037_lat_10.3039956_lon_105.2619281_alt_20.000m.png
Masks\DJI_DateTime_2024_06_02_13_43_0038_lat_10.3039632_lon_105.2619268_alt_20.009m.png
Masks\DJI_DateTime_2024_06_02_13_43_0039_lat_10.3039307_lon_105.2619253_alt_20.017m.png
Masks\DJI_DateTime_2024_06_02_13_43_0040_lat_10.3038985_lon_105.2619236_alt_20.019m.png
Masks\DJI_DateTime_2024_06_02_13_43_0041_lat_10.3038666_lon_105.2619219_alt_20.001m.png
Masks\DJI_DateTime_2024_06_02_13_43_0042_lat_10.3038342_lon_105.2619203_alt_20.049m.png
Masks\DJI_DateTime_2024_06_02_13_43_0043_lat_10.3038020_lon_105.2619186_alt_20.044m.png
Masks\DJI_DateTime_2024_06_02_13_43_0044_lat_10.3037699_lon_105.2619171_alt_20.023m.png
Masks\DJI_DateTime_2024_06_02_13_43_0045_lat_10.3037478_lon_105.2619385_alt_19.960m.png
Masks\DJI_DateTime_2024_06_02_13_43_0046_lat_10.3037496_lon_105.2619705_alt_19.973m.png
Masks\DJI_DateTime_2024_06_02_13_43_0047_lat_10.3037770_lon_105.2619830_alt_20.009m.png
Masks\DJI_DateTime_2024_06_02_13_43_0048_lat_10.3038091_lon_105.2619845_alt_20.005m.png
Masks\DJI_DateTime_2024_06_02_13_46_0100_lat_10.3048624_lon_105.2621073_alt_20.006m.png
Masks\DJI_DateTime_2024_06_02_13_46_0101_lat_10.3048303_lon_105.2621055_alt_20.021m.png
Masks\DJI_DateTime_2024_06_02_13_46_0102_lat_10.3047980_lon_105.2621037_alt_19.992m.png
Masks\DJI_DateTime_2024_06_02_13_46_0103_lat_10.3047657_lon_105.2621019_alt_19.981m.png
Masks\DJI_DateTime_2024_06_02_13_46_0104_lat_10.3047332_lon_105.2621004_alt_20.000m.png
Masks\DJI_DateTime_2024_06_02_13_46_0105_lat_10.3047014_lon_105.2620993_alt_19.998m.png
Masks\DJI_DateTime_2024_06_02_13_46_0106_lat_10.3046688_lon_105.2620979_alt_19.993m.png
Masks\DJI_DateTime_2024_06_02_13_46_0107_lat_10.3046364_lon_105.2620963_alt_19.999m.png
Masks\DJI_DateTime_2024_06_02_13_46_0108_lat_10.3046041_lon_105.2620949_alt_20.005m.png
Masks\DJI_DateTime_2024_06_02_13_47_0109_lat_10.3045719_lon_105.2620937_alt_20.010m.png
Masks\DJI_DateTime_2024_06_02_13_47_0110_lat_10.3045391_lon_105.2620921_alt_20.004m.png
Masks\DJI_DateTime_2024_06_02_13_47_0111_lat_10.3045066_lon_105.2620905_alt_20.003m.png

In [41]:
mask_dir = WEEDY_DIR / "Masks"

mask_files = list(mask_dir.glob("*.png"))

print("Total masks:", len(mask_files))

print("\nSample masks:")
for file_path in mask_files[:10]:
    print(file_path.name)

Total masks: 734

Sample masks:
DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m.png
DJI_DateTime_2024_06_02_13_42_0036_lat_10.3040274_lon_105.2619303_alt_19.998m.png
DJI_DateTime_2024_06_02_13_43_0037_lat_10.3039956_lon_105.2619281_alt_20.000m.png
DJI_DateTime_2024_06_02_13_43_0038_lat_10.3039632_lon_105.2619268_alt_20.009m.png
DJI_DateTime_2024_06_02_13_43_0039_lat_10.3039307_lon_105.2619253_alt_20.017m.png
DJI_DateTime_2024_06_02_13_43_0040_lat_10.3038985_lon_105.2619236_alt_20.019m.png
DJI_DateTime_2024_06_02_13_43_0041_lat_10.3038666_lon_105.2619219_alt_20.001m.png
DJI_DateTime_2024_06_02_13_43_0042_lat_10.3038342_lon_105.2619203_alt_20.049m.png
DJI_DateTime_2024_06_02_13_43_0043_lat_10.3038020_lon_105.2619186_alt_20.044m.png
DJI_DateTime_2024_06_02_13_43_0044_lat_10.3037699_lon_105.2619171_alt_20.023m.png

In [42]:
from PIL import Image

for file_path in mask_files[:5]:
    img = Image.open(file_path)

    print(
        file_path.name,
        "→",
        img.size,
        "→",
        img.mode
    )

DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m.png → (1280, 960) → L
DJI_DateTime_2024_06_02_13_42_0036_lat_10.3040274_lon_105.2619303_alt_19.998m.png → (1280, 960) → L
DJI_DateTime_2024_06_02_13_43_0037_lat_10.3039956_lon_105.2619281_alt_20.000m.png → (1280, 960) → L
DJI_DateTime_2024_06_02_13_43_0038_lat_10.3039632_lon_105.2619268_alt_20.009m.png → (1280, 960) → L
DJI_DateTime_2024_06_02_13_43_0039_lat_10.3039307_lon_105.2619253_alt_20.017m.png → (1280, 960) → L

In [43]:
import numpy as np
from PIL import Image

mask = Image.open(mask_files[0])

mask_array = np.array(mask)

print("Shape:", mask_array.shape)
print("Unique pixel values:", np.unique(mask_array))

Shape: (960, 1280)
Unique pixel values: [  0 255]

In [44]:
# Check the train/validation/test split files

for split in ["train", "val", "test"]:
    file_path = WEEDY_DIR / f"{split}_list.txt"

    with open(file_path, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]

    print(split, "samples:", len(lines))
    print("First 3:", lines[:3])
    print()

train samples: 438
First 3: ['DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m.JPG', 'DJI_DateTime_2024_06_02_13_42_0036_lat_10.3040274_lon_105.2619303_alt_19.998m.JPG', 'DJI_DateTime_2024_06_02_13_43_0038_lat_10.3039632_lon_105.2619268_alt_20.009m.JPG']

val samples: 148
First 3: ['DJI_DateTime_2024_06_02_13_43_0042_lat_10.3038342_lon_105.2619203_alt_20.049m.JPG', 'DJI_DateTime_2024_06_02_13_43_0044_lat_10.3037699_lon_105.2619171_alt_20.023m.JPG', 'DJI_DateTime_2024_06_02_13_46_0101_lat_10.3048303_lon_105.2621055_alt_20.021m.JPG']

test samples: 148
First 3: ['DJI_DateTime_2024_06_02_13_43_0037_lat_10.3039956_lon_105.2619281_alt_20.000m.JPG', 'DJI_DateTime_2024_06_02_13_43_0041_lat_10.3038666_lon_105.2619219_alt_20.001m.JPG', 'DJI_DateTime_2024_06_02_13_43_0045_lat_10.3037478_lon_105.2619385_alt_19.960m.JPG']

In [45]:
# Check RGB and mask filenames

rgb_dir = WEEDY_DIR / "RGB"
mask_dir = WEEDY_DIR / "Masks"

rgb_files = list(rgb_dir.glob("*.jpg"))
mask_files = list(mask_dir.glob("*.png"))

print("RGB images:", len(rgb_files))
print("Masks:", len(mask_files))

print("\nRGB sample:")
print(rgb_files[0].name)

print("\nMask sample:")
print(mask_files[0].name)

RGB images: 734
Masks: 734

RGB sample:
DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m.JPG

Mask sample:
DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m.png

In [46]:
tif_files = list(WEEDY_DIR.rglob("*.tif"))

print("Total TIFF files:", len(tif_files))

print("\nFirst 20 TIFF files:")
for file_path in tif_files[:20]:
    print(file_path.relative_to(WEEDY_DIR))

Total TIFF files: 2936

First 20 TIFF files:
Multispectral\DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m_G.TIF
Multispectral\DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m_NIR.TIF
Multispectral\DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m_R.TIF
Multispectral\DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m_RE.TIF
Multispectral\DJI_DateTime_2024_06_02_13_42_0036_lat_10.3040274_lon_105.2619303_alt_19.998m_G.TIF
Multispectral\DJI_DateTime_2024_06_02_13_42_0036_lat_10.3040274_lon_105.2619303_alt_19.998m_NIR.TIF
Multispectral\DJI_DateTime_2024_06_02_13_42_0036_lat_10.3040274_lon_105.2619303_alt_19.998m_R.TIF
Multispectral\DJI_DateTime_2024_06_02_13_42_0036_lat_10.3040274_lon_105.2619303_alt_19.998m_RE.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0037_lat_10.3039956_lon_105.2619281_alt_20.000m_G.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0037_lat_10.3039956_lon_105.2619281_alt_20.000m_NIR.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0037_lat_10.3039956_lon_105.2619281_alt_20.000m_R.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0037_lat_10.3039956_lon_105.2619281_alt_20.000m_RE.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0038_lat_10.3039632_lon_105.2619268_alt_20.009m_G.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0038_lat_10.3039632_lon_105.2619268_alt_20.009m_NIR.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0038_lat_10.3039632_lon_105.2619268_alt_20.009m_R.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0038_lat_10.3039632_lon_105.2619268_alt_20.009m_RE.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0039_lat_10.3039307_lon_105.2619253_alt_20.017m_G.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0039_lat_10.3039307_lon_105.2619253_alt_20.017m_NIR.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0039_lat_10.3039307_lon_105.2619253_alt_20.017m_R.TIF
Multispectral\DJI_DateTime_2024_06_02_13_43_0039_lat_10.3039307_lon_105.2619253_alt_20.017m_RE.TIF

In [48]:
import rasterio

sample_tif = tif_files[0]

with rasterio.open(sample_tif) as src:
    print("File:", sample_tif.name)
    print("Width:", src.width)
    print("Height:", src.height)
    print("Bands:", src.count)
    print("Data type:", src.dtypes)
    print("CRS:", src.crs)

File: DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m_G.TIF
Width: 1280
Height: 960
Bands: 3
Data type: ('uint8', 'uint8', 'uint8')
CRS: None

C:\Users\adnan\anaconda3\Lib\site-packages\rasterio\__init__.py:379: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, thread_safe=thread_safe, **kwargs)

In [49]:
import rasterio
import numpy as np

# Same sample ID ke 4 bands
sample_base = (
    "DJI_DateTime_2024_06_02_13_42_0035"
    "_lat_10.3040603_lon_105.2619317_alt_20.018m"
)

bands = ["G", "R", "RE", "NIR"]

for band in bands:
    tif_path = WEEDY_DIR / "Multispectral" / f"{sample_base}_{band}.TIF"

    with rasterio.open(tif_path) as src:
        data = src.read()

        print(f"\n{band}")
        print("Shape:", data.shape)
        print("Dtype:", data.dtype)
        print("Min:", data.min())
        print("Max:", data.max())
        print("Mean:", data.mean())

G
Shape: (3, 960, 1280)
Dtype: uint8
Min: 0
Max: 172
Mean: 54.539140625

R
Shape: (3, 960, 1280)
Dtype: uint8
Min: 16
Max: 147
Mean: 39.57585205078125

RE
Shape: (3, 960, 1280)
Dtype: uint8
Min: 19
Max: 164
Mean: 63.4092626953125

NIR
Shape: (3, 960, 1280)
Dtype: uint8
Min: 17
Max: 104
Mean: 59.272908528645836

In [50]:
sample_g = WEEDY_DIR / "Multispectral" / (
    "DJI_DateTime_2024_06_02_13_42_0035"
    "_lat_10.3040603_lon_105.2619317_alt_20.018m"
    "_G.TIF"
)

with rasterio.open(sample_g) as src:
    print("Count:", src.count)
    print("Descriptions:", src.descriptions)
    print("\nTags:")
    print(src.tags())

    for i in range(1, src.count + 1):
        print(f"Band {i} tags:", src.tags(i))

Count: 3
Descriptions: (None, None, None)

Tags:
{}
Band 1 tags: {}
Band 2 tags: {}
Band 3 tags: {}

In [51]:
from collections import defaultdict

multispectral_dir = WEEDY_DIR / "Multispectral"

# Har image ID ke available bands store karenge
image_bands = defaultdict(set)

for tif_path in multispectral_dir.glob("*.TIF"):
    filename = tif_path.stem

    # Last part G/R/RE/NIR hoga
    band = filename.split("_")[-1]

    # Band ko filename se remove karke image ID
    image_id = filename.rsplit("_", 1)[0]

    if band in {"G", "R", "RE", "NIR"}:
        image_bands[image_id].add(band)

# Summary
required_bands = {"G", "R", "RE", "NIR"}

complete_ids = []
incomplete_ids = []

for image_id, bands in image_bands.items():
    missing = required_bands - bands

    if not missing:
        complete_ids.append(image_id)
    else:
        incomplete_ids.append((image_id, sorted(bands), sorted(missing)))

print("Total unique image IDs:", len(image_bands))
print("Complete 4-band sets:", len(complete_ids))
print("Incomplete sets:", len(incomplete_ids))

Total unique image IDs: 734
Complete 4-band sets: 734
Incomplete sets: 0

In [52]:
print("\nINCOMPLETE IMAGE SETS")
print("=" * 80)

for image_id, available, missing in incomplete_ids:
    print(f"\nID: {image_id}")
    print("Available:", available)
    print("Missing:", missing)

INCOMPLETE IMAGE SETS
================================================================================

In [53]:
print("\nBAND COUNTS")
print("=" * 40)

for band in ["G", "R", "RE", "NIR"]:
    count = sum(band in bands for bands in image_bands.values())
    print(f"{band}: {count}")

BAND COUNTS
========================================
G: 734
R: 734
RE: 734
NIR: 734

In [60]:
import rasterio
import numpy as np

# Folder se pehli Green band file auto-pick karein (dono extension check karke)
g_files = list(ms_dir.glob("*_G.TIF")) + list(ms_dir.glob("*_G.tif"))

if g_files:
    sample_g_path = g_files[0]
    # Automatic sample_base extraction
    base_name = sample_g_path.name.replace("_G.TIF", "").replace("_G.tif", "")
    print(f"Found Sample: {base_name}")

    def read_band(suffix):
        path = ms_dir / f"{base_name}{suffix}"
        if not path.exists():
            path = ms_dir / f"{base_name}{suffix.lower()}"
        with rasterio.open(path) as src:
            return src.read(1).astype(np.float32)

    G = read_band("_G.TIF")
    R = read_band("_R.TIF")
    RE = read_band("_RE.TIF")
    NIR = read_band("_NIR.TIF")

    print("Successfully loaded all 4 bands!")
    print(f"Band Shape: {G.shape}")
else:
    print("Multispectral folder me koi file nahi mili!")

Found Sample: DJI_DateTime_2024_06_02_13_42_0035_lat_10.3040603_lon_105.2619317_alt_20.018m
Successfully loaded all 4 bands!
Band Shape: (960, 1280)

C:\Users\adnan\anaconda3\Lib\site-packages\rasterio\__init__.py:379: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, thread_safe=thread_safe, **kwargs)

In [62]:
# NDVI
ndvi_denominator = NIR + R

NDVI = np.divide(
    NIR - R,
    ndvi_denominator,
    out=np.zeros_like(NIR),
    where=ndvi_denominator != 0
)

# NDRE
ndre_denominator = NIR + RE

NDRE = np.divide(
    NIR - RE,
    ndre_denominator,
    out=np.zeros_like(NIR),
    where=ndre_denominator != 0
)

print("NDVI")
print("Shape:", NDVI.shape)
print("Min:", NDVI.min())
print("Max:", NDVI.max())
print("Mean:", NDVI.mean())

print("\nNDRE")
print("Shape:", NDRE.shape)
print("Min:", NDRE.min())
print("Max:", NDRE.max())
print("Mean:", NDRE.mean())

NDVI
Shape: (960, 1280)
Min: -0.5857988
Max: 0.5
Mean: 0.21112095

NDRE
Shape: (960, 1280)
Min: -0.35
Max: 0.24705882
Mean: -0.021947078

In [63]:
from pathlib import Path

ndvi_dir = PROJECT_ROOT / "data" / "processed" / "ndvi"
ndre_dir = PROJECT_ROOT / "data" / "processed" / "ndre"

ndvi_dir.mkdir(parents=True, exist_ok=True)
ndre_dir.mkdir(parents=True, exist_ok=True)

# Sabhi G-band files
g_files = list(ms_dir.glob("*_G.TIF")) + list(ms_dir.glob("*_G.tif"))

processed = 0
skipped = 0

for g_path in g_files:

    base_name = g_path.name.rsplit("_G", 1)[0]

    r_path = ms_dir / f"{base_name}_R.TIF"
    re_path = ms_dir / f"{base_name}_RE.TIF"
    nir_path = ms_dir / f"{base_name}_NIR.TIF"

    # Agar lowercase extension ho
    if not r_path.exists():
        r_path = ms_dir / f"{base_name}_R.tif"
    if not re_path.exists():
        re_path = ms_dir / f"{base_name}_RE.tif"
    if not nir_path.exists():
        nir_path = ms_dir / f"{base_name}_NIR.tif"

    if not (r_path.exists() and re_path.exists() and nir_path.exists()):
        skipped += 1
        continue

    with rasterio.open(r_path) as src:
        R = src.read(1).astype(np.float32)

    with rasterio.open(re_path) as src:
        RE = src.read(1).astype(np.float32)

    with rasterio.open(nir_path) as src:
        NIR = src.read(1).astype(np.float32)

    # NDVI
    denominator = NIR + R
    NDVI = np.divide(
        NIR - R,
        denominator,
        out=np.zeros_like(NIR),
        where=denominator != 0
    )

    # NDRE
    denominator = NIR + RE
    NDRE = np.divide(
        NIR - RE,
        denominator,
        out=np.zeros_like(NIR),
        where=denominator != 0
    )

    # Save as NumPy arrays
    np.save(ndvi_dir / f"{base_name}_NDVI.npy", NDVI)
    np.save(ndre_dir / f"{base_name}_NDRE.npy", NDRE)

    processed += 1

print("Processing complete!")
print("Processed:", processed)
print("Skipped:", skipped)

Processing complete!
Processed: 1468
Skipped: 0